= Barman
:toc:
:toc-title: 목차

== 1. barman 개요
barman(Backup and Recovery Manager for PostgreSQL)는 PostgreSQL 서버의 장애 복구를 위한 관리 도구이며 여러 대의 서버를 원격으로 백업, 복구가 가능합니다.

== 2. barman 설치

=== 2.1 설치요구사항

[width 300, options=header]
.시스템 요구사항
|===
|OS|Linux / Unix
|Python| 3.4 버전 이상
.4+|Python 모듈
|argcomplete
|psycopg 2.4.2 버전 이상
|python-dateutil
|setuptools
|PostgreSQL|8.3 버전 이상
|rsync|3.0.4 버전 이상
|===

[width 300, options=header, cols="^"]
.백업 서버 필요 라이브러리
|===
|라이브러리명
|make
|gcc
|python3
|python3-devel
|python3-pip
|python3-libs
|postgresql-libs
|postgresql-devel
|openssl-devel
|libxml2-devel
|lz4-devel
|libzstd-devel
|bzip2-devel
|libyaml-devel
|===
`*sudo yum install make gcc postgresql-libs postgresql-devel openssl-devel libxml2-devel lz4-devel libzstd-devel bzip2-devel libyaml-devel*`

[width 300, options=header, cols="^"]
.PostgreSQL 운영 서버 필요 라이브러리
|===
|라이브러리명
|postgresql-libs
|openssl-devel
|libxml2-devel
|lz4-devel
|libzstd-devel
|bzip2-devel
|libyaml-devel
|===
`*sudo yum install postgresql-libs openssl-devel libxml2-devel lz4-devel libzstd-devel bzip2-devel libyaml-devel*` + 
 + 
추가적으로, 백업 서버와 PostgreSQL 운영 서버간에 SSH authentication key 등록이 필요합니다. + 
 + 
SSH key 등록은 아래의 문서를 참조하시기 바랍니다. + 
*SSH authentication key 등록* + 


=== 2.2 설치
==== 설치 환경
.*백업 서버 환경*
|=======
| OS | CentOS 7.6
| CPU | 4 Cores
| MEM | 8 GB
| Barman Version | 2.19
|=======

.*PostgreSQL 운영 서버 환경*
|=======
| OS | CentOS 7.6
| CPU | 4 Cores
| MEM | 8 GB
| PostgreSQL Version | PostgreSQL 14.3
|=======

==== 필요 라이브러리 설치
1. argcomplete +
`sudo pip3 install argcomplete` + 

2. psycopg2 + 
`sudo pip3 install psycopg2`

3. python-dateutil + 
`sudo pip3 install python-dateutil` + 

==== barman 설치
[source, sh]
----
# 패스워드를 1234를 기준으로 설치를 진행하겠습니다.
# PostgreSQL barman 유저 생성
createuser -P barman
1234
1234

# .pgpass 생성
vi ~/.pgpass
# hostname:port:databasename:username:userpassword
# 여기에선 임의로 pg 서버의 ip를 192.168.0.2 이라고 하겠습니다.
192.168.0.2:5432:*:barman:1234

# .pgpass 권한 변경
chmod 600 ~/.pgpass

# 권한 부여
GRANT EXECUTE ON FUNCTION pg_start_backup(text, boolean, boolean) to barman;
GRANT EXECUTE ON FUNCTION pg_stop_backup() to barman;
GRANT EXECUTE ON FUNCTION pg_stop_backup(boolean, boolean) to barman;
GRANT EXECUTE ON FUNCTION pg_switch_wal() to barman;
GRANT EXECUTE ON FUNCTION pg_create_restore_point(text) to barman;

GRANT pg_read_all_settings TO barman;
GRANT pg_read_all_stats TO barman;

# Barman 최신 릴리즈 다운로드
wget https://github.com/EnterpriseDB/barman/archive/refs/tags/release/2.19.tar.gz

# 압축 해제
tar xvzf 2.19.tar.gz
cd barman-release-2.19

# 빌드 & 인스톨
sudo python3 ./setup.py build
sudo python3 ./setup.py install

# config 디렉토리 생성 및 샘플파일 복사
sudo mkdir -p /etc/barman.d
sudo mkdir -p /var/lib/barman

chown hypersql:hypersql /etc/barman.d
chown hypersql:hypersql /var/lib/barman

cp doc/barman.conf /etc
cp doc/barman.d/* /etc/barman.d

## 간단한 테스트를 할 수 있는 설정 방법은 6. 테스트 항목에 있습니다.
---- 

== 3. configure file 옵션

- `*active* [Server]` +
** 기본값 : True + 
** True로 운용시 모든 운영에 필요한 기능이 사용됩니다. + 
** False로 운용시 서버를 진단하는데 사용 가능하지만 백업 실행 또는 WAL archiving이 일시적으로  비활성화 됩니다. + 
** Barman 서버에 새로운 Postgres Server를 추가해줄 시 false를 사용해서 오류가 없는지 확인 후 true로 변경하는 것을 권장 합니다. + 

- `*archiver* [Global / Server]` + 
** 기본값 True + 
** archive_command를 사용하는 Continous Log Shipping(WAL archiving) 허용 여부를 결정 합니다.  + 
** True값 사용 시 Barman이 PostgreSQL Server에 대한 지속적인 WAL archiving이 있을 것으로 예상하여 Postgres 서버의 WAL파일의 관리(압축 포함)와 검사를 활성화 합니다. + 
** False값 사용 시 Continous Log Shipping을 사용하지 않습니다. + 
 
- `*archiver_batch_size* [ Global / Server ]` + 
** Archiver process의 배치 처리 사이즈를 지정하는 옵션 + 
** 0보다 큰 값으로 설정하게 되면, Archiver process의 실행당 처리 WAL segments 갯수가 제한 됩니다.
** 0보다 작은 값일 경우 Archiver process의 WAL 대기열 큐를 한번에 모두 처리 합니다.   + 

- `*backup_directory* [ Server ]` + 
** 백업 데이터가 저장되는 디렉토리를 지정 합니다. +  

- `*backup_method* [ Global / Server ]` + 
** 기본값 :  rsync + 
** 백업 실행에 사용되는 Barman 메소드 지정 합니다. + 
*** rsync : SSH + rsync를 사용하여 백업(SSH Command 작성 필요) + 
*** postgres : pg_basebackup을 사용하여 백업 + 
*** local-rsync : barman과 PostgreSQL이 같은 서버에 있는 것으로 간주하고 rsync를 사용하여 백업 + 

- `*backup_options* [ Global / Server ]`
** 기본값 : backup_method에 따라 다르게 설정 됩니다. + 
*** rsync일 때 : exclusive_backup +
*** postgres일 때 : concurrent_backup + 
** 이 옵션은 barman을 이용한 PostgreSQL 백업시 barman과 PostgreSQL의 상호 작용 방식을 제어 합니다. + 
** exclusive_backup사용 시 barman은 pg_start_backup / pg_stop_backup을 사용하여 백업 합니다. + 
** concurrent_backup사용 시 9.2 - 9.5 버전을 사용한다면 pgespresso 모듈이 PostgreSQL 서버에 설치되어야 하며, 9.6 버전부터는 새로운 PostgreSQL API를 사용하여 대기 서버로부터 백업을 수행  합니다. + 
 
- `*bandwidth_limit* [ Global / Server ]` + 
** 최대 전송 속도를 지정하는 옵션이며 kB/s 단위로 지정 합니다. + 
** 0을 입력시 속도 제한이 없음을 의미 합니다. + 

- `*barman_home* [ Global ]` + 
** Barman의 main data 디렉토리를 설정 합니다. + 

- `*barman_lock_directory* [ Global ]` + 
** 기본값 : %(barman_home)s + 
** lock을 위한 디렉토리 설정 합니다. +  
 
- `*basebackup_retry_sleep* [ Global / Server ]`  + 
** 기본값 : 30 + 
** 복사에 실패한 경우 재시도 하기 까지 기다리는 시간 입니다. +
** Backup and Recovery 명령 모두에서 사용 됩니다. 
** 초 단위이며 입력 값은 양의 정수 입니다. + 
 
- `*basebackup_retry_times* [ Global / Server ]` +
** 기본값 : 0 +  
** base backup 카피본에 대한 재시도 횟수 입니다. +
** Backup and Recovery 명령 모두에서 사용 됩니다. +  
** 입력 값은 양의 정수 입니다. + 

- `*basebackups_directory* [ Server ]`  + 
** 기본적으로 backup data가 저장될 경로 입니다. + 
 
- `*check_timeout* [ Global / Server ]` + 
** 기본값 :  30 + 
** Barman check 명령어의 각 서버당 최대 실행 시간을 지정 합니다. + 
** 0으로 설정시 timeout을 사용하지 않습니다. + 
** 초 단위이며 입력 값은 양의 정수 입니다. + 

- `*compression* [ Global / Server ]` + 
** WAL파일 압축에 사용할 알고리즘을 지정 합니다. + 
** 지정 가능한 알고리즘으로는 gzip, bzip2, pigz, pygzip, pybzip2이 있습니다.  + 
** 알고리즘에 사용시 해당 알고리즘의 패키지들이 설치되어 있어야 사용 가능 합니다. + 

- `*conninfo* [ Server ]` + 
** PostgreSQL Server 연결시에 필요한 값들을 지정 합니다. + 
** libpq 연결시와 동일한 형식을 사용합니다. + 
** host, hostaddr, port, dbname, user, password가 사용 됩니다. + 

- `*create_slot* [ Global / Server ]` + 
** 기본 값 : manual + 
** auto로 설정하면, slot_name을 지정했을 때, barman은 Replication slot이 없을 경우 생성을 시도 합니다.
** manual로 설정 시 replication slot을 사용자가 직접 생성해야 합니다.

- `*custom_compression_filter* [ Global / Server ]` + 
** WAL 파일 압축 시 사용자 정의 알고리즘을 사용 하도록 하는 옵션 입니다. + 

- `*custom_compression_magic* [ Global / Server ]` + 
** 사용자 정의 압축 알고리즘 사용시에, WAL 파일의 사전 압축 여부를 체크할 수 있도록 구성할 수 있는 옵션 입니다. +
** 지정하지 않을 경우, WAL 파일을 아카이빙 할 때 WAL 파일이 한번 더 압축될 수 있습니다. + 

- `*custom_decompression_filter* [ Global / Server ]` + 
** WAL 파일 압축 해제시 사용자 정의 알고리즘을 사용 하도록 하는 옵션 입니다. + 
** 반드시 WAL 파일 압축 방식과 동일한 해제 알고리즘을 사용해야 합니다. + 

- `*description* [ Server ]` + 
** 서버에 대한 설명을 적는 옵션 입니다. + 

- `*errors_directory*` [ 추후 수정 예정 ]+ 
** 오류가 있는 WAL 파일을 저장할 폴더 입니다. + 
** Streaming과 Log Shipping을 동시에 사용할 경우 오류가 발생할 수 있습니다. +
*** Ex) 0001 WAL가 Streaming 되었는데, Archiver process가 0001을 Archiving 할 경우 +   

- `*forward_config_path*` + 
** 추후 수정 예정. + 

Parameter which determines whether a passive node should forward its configuration file path to its primary node during cron or sync-info commands. Set to true if you are invoking barman with the -c/--config option and your configuration is in the same place on both the passive and primary barman servers. Defaults to false.

- `*immediate_checkpoint* [ Global / Server ]` + 
** 기본값 :  false + 
** 백업 시작시 checkpoint 여부를 설정 합니다. + 
** true로 설정시 백업 시작시에 checkpoint를 즉시 수행하도록 요청 합니다. + 
** false로 설정시 PostgreSQL서버의 checkpoint_completion_target값 설정에 따라 체크포인트에 대한 I/O 작업량이 제한됩니다. + 
 
- `*incoming_wals_directory* [ Server ]` + 
** Log Shipping(Archiving) 된 WAL 파일을 저장할 디렉토리 입니다. + 
** *archiver 설정을 활성화 해야 사용 가능 합니다.* + 

- `*last_backup_maximum_age* [ Global / Server ]` + 
** 기본 값 : 비어있음(empty)
** 마지막 백업이 최신 백업인지를 판단할 수 있도록 기간을 설정하는 옵션 입니다. + 
** 최신 백업이 현재를 기준으로 설정한 기간보다 오래 된 경우 barman check 명령어 실행시 error를 발생시킵니다. + 
** 값이 비어 있는 경우(empty) 마지막 백업을 항상 유효한 최신 백업인 것으로 간주 합니다. + 
*** 문법 : "i (DAYS | WEEKS | MONTHS)"  (i는 정수 값이며, 0보다 크게 설정 해야 합니다) + 

- `*last_backup_minimum_size* [ Global / Server ]` + 
** 기본 값 : 비어있음(empty)
** 최신 백업이 성공했는지 판단하기 위해 백업의 최소 용량 제한을 지정 합니다. + 
** 최신 백업의 용량이 설정한 값 보다 작을 경우, barman check 명령어 실행시 error를 발생 시킵니다. + 
** 값이 비어 있는 경우(empty) 마지막 백업을 항상 유효한 최신 백업인 것으로 간주 합니다. + 
*** 문법 : "i (k | Ki | M | Mi | G | Gi | T | Ti)"  (i는 정수 값이며, 0보다 크게 설정 해야 합니다.) + 
*** M, Mi 처럼 i가 붙은 경우의 차이는 SI 규정과 IEC 규정중 어떤 것을 따랐는지 표기하는 것이며, 아래의 예시와 같은 차이를 가집니다.
**** M=Mega=1,000,000 | Mi=MegaByte=1,048,576 

- `*last_wal_maximum_age* [ Global / Server ]` + 
** 기본 값 : 비어있음(empty)
** Log Shipping(Archiving)된 WAL 파일이 유효한지 판단할 수 있도록 기간을 지정 합니다 + 
** 마지막으로 Archiving된 WAL 파일이 현재를 기준으로 설정한 기간 보다 오래된 경우 barman check 명령어 실행시 error를 발생 시킵니다. + 
** 값이 비어 있는 경우(empty) WAL 파일의 수명을 체크하지 않습니다. + 
*** 문법 : "i (DAYS | WEEKS | MONTHS)"  (i는 정수 값이며, 0보다 크게 설정 해야 합니다.) + 

- `*log_file* [ Global ]` + 
** Barman의 log파일을 저장할 디렉토리 입니다. + 

- `*log_level* [ Global ]` + 
** Logging Level을 설정하는 옵션입니다. +
** 설정 가능한 레벨은 아래와 같습니다. +
*** DEBUG
*** INFO
*** WARNING
*** ERROR
*** CRITICAL

- `*max_incoming_wals_queue* [ Global / Server ]` + 
** 기본값 : None (Disabled) +
** barman check 명령어가 error를 반환하기 전에 허용되는 큐(Streaming, Archiving pool 둘 다)에 들어갈 수 있는 WAL 파일의 최대 갯수를 지정 하는 옵션입니다. +

- `*minimum_redundancy* [ Global / Server ]` + 
** 기본값 :  0 + 
** 보존 할 백업의 최소 갯수 입니다. + 

- `*network_compression* [ Global / Server ]` + 
** 기본값 :  false + 
** 네트워크 전송에 대한 데이터 압축 여부를 설정 합니다. + 

- `*parallel_jobs* [ Global / Server ]` + 
** 기본값 :  1 + 
** 백업 및 복구시에 병렬 처리를 수행할 최대 worker의 수를 지정 합니다. + 
*** *backup_method가 rsync일 경우에만 사용이 가능 합니다.* + 

- `*path_prefix* [ Global / Server ]` + 
** Barman이 실행 파일을 찾을 절대 경로 입니다. +
** 콜론(:)으로 구분하여 여러개의 경로를 입력할 수 있습니다. 
*** *PATH 환경 변수 보다 먼저 확인되는 옵션 입니다.* + 

- `*post_archive_retry_script* [ Global / Server ]` +
** WAL 파일이 아카이브 된 후에 실행할 Hook Script 입니다. + 
** 조건[결과 값 : SUCCESS(0), ABORT_CONTINUE(62), ABORT_STOP(63)]을 만족할 때 까지 재실행 됩니다. + 
*** 현재 버전에서는 ABORT_CONTINUE(62), ABORT_STOP(63) 결과 값 둘 다 같은 동작을 합니다.

- `*post_archive_script* [ Global / Server ]` + 
** WAL 파일이 아카이브 된 후에 실행할 Hook Script 입니다. +   
** WAL 파일이 아카이브 된 후에, *post_archive_retry_script가 먼저 실행되며*, 이후에 이 Hook Script가 실행 됩니다. + 
*** 실행 결과에 상관 없이, 한 번만 실행 됩니다.

- `*post_backup_retry_script* [ Global / Server ]` + 
** 백업 후에 실행할 Hook Script 입니다. +    
** 조건[결과 값 : SUCCESS(0), ABORT_CONTINUE(62), ABORT_STOP(63)]을 만족할 때 까지 재실행 됩니다. + 
*** 현재 버전에서는 ABORT_CONTINUE(62), ABORT_STOP(63) 결과 값 둘 다 같은 동작을 합니다.

- `*post_backup_script* [ Global / Server ]` + 
** 백업 후에 실행할 Hook Script 입니다. +    
** 백업 후에, *post_backup_retry_script가 먼저 실행 되며*, 이후에 이 Hook Script가 실행 됩니다. + 
*** 실행 결과에 상관 없이, 한 번만 실행 됩니다.

- `*post_delete_retry_script* [ Global / Server ]` + 
** 백업 삭제 후에 실행할 Hook Script 입니다. +    
** 조건[결과 값 : SUCCESS(0), ABORT_CONTINUE(62), ABORT_STOP(63)]을 만족할 때 까지 재실행 됩니다. + 
*** 현재 버전에서는 ABORT_CONTINUE(62), ABORT_STOP(63) 결과 값 둘 다 같은 동작을 합니다.

- `*post_delete_script* [ Global / Server ]` + 
** 백업 삭제 후에 실행할 Hook Script 입니다. +    
** 백업 삭제 후에, *post_delete_retry_script가 먼저 실행 되며*, 이후에 이 Hook Script가 실행 됩니다. + 
*** 실행 결과에 상관 없이, 한 번만 실행 됩니다.

- `*post_recovery_retry_script* [ Global / Server ]` + 
** 복구 작업 후에 실행할 Hook Script 입니다. +    
** 조건[결과 값 : SUCCESS(0), ABORT_CONTINUE(62), ABORT_STOP(63)]을 만족할 때 까지 재실행 됩니다. + 
*** 현재 버전에서는 ABORT_CONTINUE(62), ABORT_STOP(63) 결과 값 둘 다 같은 동작을 합니다.

- `*post_recovery_script* [ Global / Server ]` + 
** 복구 작업 후에 실행할 Hook Script 입니다. +    
** 복구 작업 후에, *post_recovery_retry_script가 먼저 실행 되며*, 이후에 이 Hook Script가 실행 됩니다. + 
*** 실행 결과에 상관 없이, 한 번만 실행 됩니다.

- `*post_wal_delete_retry_script* [ Global / Server ]` + 
** WAL 파일이 제거된 후에 실행할 Hook Script 입니다. +    
** 조건[결과 값 : SUCCESS(0), ABORT_CONTINUE(62), ABORT_STOP(63)]을 만족할 때 까지 재실행 됩니다. + 
*** 현재 버전에서는 ABORT_CONTINUE(62), ABORT_STOP(63) 결과 값 둘 다 같은 동작을 합니다.

- `*post_wal_delete_script* [ Global / Server ]` + 
** WAL 파일이 제거된 후에 실행할 Hook Script 입니다. +    
** WAL 파일이 제거된 후에, *post_wal_delete_retry_script가 먼저 실행 되며*, 이후에 이 Hook Script가 실행 됩니다. + 
*** 실행 결과에 상관 없이, 한 번만 실행 됩니다.




- `*pre_archive_retry_script* [ Global / Server ]` +
** WAL 파일이 아카이브 되기 전에 실행할 Hook Script 입니다. + 
** WAL 파일이 아카이브 되기 전에, *pre_archive_script가 먼저 실행되며*, 이후에 이 Hook Script가 실행 됩니다. + 
** 조건[결과 값 : SUCCESS(0), ABORT_CONTINUE(62), ABORT_STOP(63)]을 만족할 때 까지 재실행 됩니다. + 
*** ABORT_STOP(63) 결과 값을 받을 경우, 더 이상 재시도 하지 않고 WAL 파일 Archiving을 중단 합니다.

- `*pre_archive_script* [ Global / Server ]` + 
** WAL 파일이 아카이브 되기 전에 실행할 Hook Script 입니다. +   
*** 실행 결과에 상관 없이, 한 번만 실행 됩니다.

- `*pre_backup_retry_script* [ Global / Server ]` + 
** 백업 전에 실행할 Hook Script 입니다. + 
** 백업 전에, *pre_backup_script가 먼저 실행되며*, 이후에 이 Hook Script가 실행 됩니다. +    
** 조건[결과 값 : SUCCESS(0), ABORT_CONTINUE(62), ABORT_STOP(63)]을 만족할 때 까지 재실행 됩니다. + 
*** ABORT_STOP(63) 결과 값을 받을 경우, 더 이상 재시도 하지 않고 백업을 중단 합니다.

- `*pre_backup_script* [ Global / Server ]` + 
** 백업 전에 실행할 Hook Script 입니다. +    
*** 실행 결과에 상관 없이, 한 번만 실행 됩니다.

- `*pre_delete_retry_script* [ Global / Server ]` + 
** 백업 삭제 전에 실행할 Hook Script 입니다. +    
** 백업 삭제 전에, *pre_delete_script가 먼저 실행되며*, 이후에 이 Hook Script가 실행 됩니다. +    
** 조건[결과 값 : SUCCESS(0), ABORT_CONTINUE(62), ABORT_STOP(63)]을 만족할 때 까지 재실행 됩니다. + 
*** ABORT_STOP(63) 결과 값을 받을 경우, 더 이상 재시도 하지 않고 백업을 중단 합니다.

- `*pre_delete_script* [ Global / Server ]` + 
** 백업 삭제 전에 실행할 Hook Script 입니다. + 
*** 실행 결과에 상관 없이, 한 번만 실행됩니다.

- `*pre_recovery_retry_script* [ Global / Server ]` + 
** 복구 작업 전에 실행할 Hook Script 입니다. +    
** 복구 작업 전에, *pre_recovery_script가 먼저 실행되며*, 이후에 이 Hook Script가 실행 됩니다. + 
** 조건[결과 값 : SUCCESS(0), ABORT_CONTINUE(62), ABORT_STOP(63)]을 만족할 때 까지 재실행 됩니다. + 
*** ABORT_STOP(63) 결과 값을 받을 경우, 더 이상 재시도 하지 않고 백업을 중단 합니다.

- `*pre_recovery_script* [ Global / Server ]` + 
** 복구 작업 전에 실행할 Hook Script 입니다. +    
*** 실행 결과에 상관 없이, 한 번만 실행 됩니다.

- `*pre_wal_delete_retry_script* [ Global / Server ]` + 
** WAL 파일을 제거하기 전에 실행할 Hook Script 입니다. +    
** WAL 파일을 제거하기 전에, *pre_wal_delete_script가 먼저 실행되며*, 이후에 이 Hook Script가 실행 됩니다. +
** 조건[결과 값 : SUCCESS(0), ABORT_CONTINUE(62), ABORT_STOP(63)]을 만족할 때 까지 재실행 됩니다. +
*** ABORT_STOP(63) 결과 값을 받을 경우, 더 이상 재시도 하지 않고 백업을 중단 합니다. 

- `*pre_wal_delete_script* [ Global / Server ]` + 
** WAL 파일을 제거하기 전에 실행할 Hook Script 입니다. +    
*** 실행 결과에 상관 없이, 한 번만 실행됩니다.

- `*primary_ssh_command* [ Global ]` + 
** 기본값 : 비어 있음(empty)
** 설정시에 Barman 서버가 passive node가 되며, primary server에 접속시에 사용할 command를 지정하는 옵션 입니다. (Connection command) + 
** passive node에서는, 백업 대상이 PostgreSQL 서버가 아닌 다른 서버의 barman에 백업되어 있는 백업입니다. (동기화, 이중화) +
*** PG 서버의 백업도 관리 하면서 동시에, 다른 Barman서버의 passive node로 동작하는 혼합 방식도 사용이 가능 합니다. 

- `*recovery_options* [ Global / Server ]` + 
** 기본값 :  비어 있음(empty) + 
** 복구에 사용되는 옵션으로, 현재 get-wal 옵션만 지원 합니다. + 
** get-wal 옵션을 사용시, 복구시에 barman get-wal 명령을 통해서 WAL파일들을 아카이브에서 직접 가져올 수 있도록 restore_command를 생성해 줍니다. + 
** 콤마(,)를 구분자로 사용하여, 여러 아카이브에서 동시에 가져올 수 있습니다.  + 
 
- `*retention_policy* [ Global / Server ]` + 
** 기본값 :  비어 있음(empty) + 
** 백업 및 WAL 아카이브에 대한 보존 정책을 설정하며 값을 비워둘 경우 보존정책을 설정 하지 않습니다. +
** 중복성 기반의 보존 정책과 기간 기반의 보존 정책을 설정할 수 있습니다. 
*** 중복성 기반의 보존 정책 문법 : "REDUNDANCY i" (i는 정수이고 0보다 커야 하며, 유지할 백업 갯수를 의미합니다). + 
*** 기간 기반의 보존 정책 문법 : "RECOVERY WINDOW OF i DAYS",  “RECOVERY WINDOW OF i WEEKS”,  “RECOVERY WINDOW OF i MONTHS” (i는 정수이고 0보다 커야하며, 유지할 기간을 의미합니다). + 

- `*retention_policy_mode* [ Global / Server ]` + 
** 현재 auto 옵션만 지원 합니다. + 
 
- `*reuse_backup* [ INCREMENTAL_TYPE ] [ Global / Server ]` + 
** 기본 값 : off(disabled)
** 증분 백업을 사용할 경우 어떤 방식으로 증분 백업을 할지 설정하는 옵션 입니다. + 
*** off : 증분 백업을 사용하지 않습니다. + 
*** copy : 변경되지 않은 파일에 대해서 복사를 하는 방식으로 백업본을 재사용 합니다. (백업에 걸리는 시간이 단축 됩니다.) + 
*** link : 변경되지 않은 파일에 대해서 Hard link를 연결하는 방식으로 백업본을 재사용 합니다. (백업 에 걸리는 시간과 공간을 줄여 줍니다.). + 
**** *OS에서 Hard link를 지원해야 합니다* + 

- `*slot_name* [ Global / Server ]` + 
** 기본값 : None(disabled) + 
** *streaming_archiver가 on으로 설정된 경우* receive-wal 명령에서 사용할 물리적 Replication Slot Name 입니다. + 
** PostgreSQ 9.4 버전부터 사용 됩니다. + 

- `*ssh_command* [ Server ]` + 
** SSH를 사용하여, barman 서버에서 PostgreSQL 서버로 접속할 때 사용할 Command 입니다. + 

- `*streaming_archiver* [ Global / Server ]` + 
** 기본값 : off +
** PostgreSQL의 스트리밍 프로토콜을 사용하여 PostgreSQL 서버로부터 트랜잭션 로그를 받아올지 설정 하는 옵션 입니다. + 
** on으로 설정시 Barman은 PATH(path_prefix 옵션 확인)에서 pg_receivewal를 찾아서 PostgreSQL 서버에 Streaming 연결을 합니다. + 
** 이것은 WAL 파일의 관리 (압축 포함)뿐만 아니라 연결에 대한 검사를 활성화 합니다. + 
** off로 설정시 barman은 WAL 파일을 Archiving에만 의존하며 실행중이던 pg_receivewal를 종료 합니다. +  

- `*streaming_archiver_batch_size* [ Global / Server ]` + 
** 기본값 : 0(unlimited) +
** Archiver process의 배치 처리 사이즈를 지정하는 옵션 입니다. + 
** 0보다 큰 값으로 설정하게 되면, archive-wal process의 실행당 처리 WAL segments 갯수가 제한 됩니다.
** 0보다 작은 값일 경우 archive-wal process의 WAL 대기열 큐를 한번에 모두 처리 합니다.   + 

- `*streaming_archiver_name* [ Global / Server ]` +
** 기본값 : barman_receive_wal 
** receive-wal Command 실행시 사용할 application_name 입니다. + 
** pg_receivexlog 9.3 버전 이상 또는 pg_receivewal만 사용 가능한 옵션 입니다. + 

- `*streaming_backup_name*` [ Global / Server] +
** 기본값 : barman_streaming_backup 
** pg_basebackup Command 실행시 사용할 application_name 입니다. + 
** pg_basebackup 9.3 버전 이상만 사용 가능 합니다. + 
 
- `*streaming_conninfo* [ Server ]` + 
** 기본값 : 비어 있음(empty)
** Postgres 서버에 streaming replication protocol 연결시 사용할 conninfo 입니다. +
*** 값을 넣지 않을 경우, conninfo 옵션에 설정된 정보를 참조 합니다.
 
- `*streaming_wals_directory* [ Server ]` + 
** WAL streaming시 WAL 파일이 저장될 디렉토리 입니다. +
*** streaming_archiver가 on이어야 합니다. 

- `*tablespace_bandwidth_limit* [ Global / Server ]` + 
** 기본값 : 0(unlimited) +
** 테이블스페이스를 백업할 때 전송 속도를 제한할 수 있는 옵션 입니다. 
** 단위 :  kB/s
*** 사용 문법 : 테이블명:제한속도 +
*** 여러개 입력 시 콤마(,)로 구분 합니다.
**** Ex) 테이블명:제한속도,테이블명:제한속도 +

- `*wal_retention_policy* [ Glocal / Server ]` + 
** 아카이브 된 WAL의 보존 정책을 설정 합니다.
** 현재는 오직 MAIN만 사용 가능 합니다. + 
 
- `*wals_directory* [ Server ]` + 
** WAL파일들을 포함하는 디렉토리 입니다. + 

== 4. Hook Script 
Hook Script에서 사용할 수 있는 예약어 입니다. + 
Retry Hook Script의 결과 값은 Barman에 의해서 체크되며, 로그 파일에도 기록이 남습니다. + 

공통 예약어:
|===
|BARMAN_CONFIGURATION|configuration file used by barman
|BARMAN_ERROR|error message, if any (only for the 'post' phase)
|BARMAN_PHASE|'pre' or 'post'
|BARMAN_RETRY|1 if it is a retry script (from 1.5.0), 0 if not
|BARMAN_SERVER|name of the server
|===


백업 Hook script에 사용되는 예약어:
|===
|BARMAN_BACKUP_DIR|backup destination directory
|BARMAN_BACKUP_ID|ID of the backup
|BARMAN_PREVIOUS_ID|ID of the previous backup (if present)
|BARMAN_NEXT_ID|ID of the next backup (if present)
|BARMAN_STATUS|status of the backup
|BARMAN_VERSION|version of Barman
|===


아카이브 Hook script에 사용되는 예약어:
|===
|BARMAN_SEGMENT|name of the WAL file
|BARMAN_FILE|full path of the WAL file
|BARMAN_SIZE|size of the WAL file
|BARMAN_TIMESTAMP|WAL file timestamp
|BARMAN_COMPRESSION|type of compression used for the WAL file
|===

복구 Hook script에 사용되는 예약어:
|===
|BARMAN_DESTINATION_DIRECTORY|the directory where the new instance is recovered
|BARMAN_TABLESPACES|tablespace relocation map (JSON, if present)
|BARMAN_REMOTE_COMMAND|secure shell command used by the recovery (if present)
|BARMAN_RECOVER_OPTIONS|recovery additional options (JSON, if present)
|===

== 5. command
 
=== *커맨드 사용 형식* 
 * `barman [OPTIONS] COMMAND` + 

=== *커맨드 수행 결과 값*
 * 커맨드 실행에 성공 했을 경우 0을 반환 합니다.
  
=== *OPTIONS* + 
* -h, -help
** help 메시지를 출력 합니다.
* -v, -version
** 버전확인
* -c CONFIG, --config CONFIG 
** 사용자 지정 설정 파일을 사용하고 싶을 때 사용 합니다.
* --color {never,always,auto}, --colour {never, always, auto}
** 기본값 : auto
** 출력에 색상을 사용할지 설정 합니다.
* -q, -quiet 
** 아무 출력도 하지 않습니다. +  
cron을 이용해서 script를 사용할 때 유용한 옵션 입니다.
* -d, --debug
** 기본값 : false
** 디버그에 필요한 수준의 출력을 합니다.
* --log-level {NOTSET, DEBUG, INFO, WARNING, ERROR, CRITICAL}
** 설정 파일된 로그 레벨을 무시하고 레벨을 설정할 수 있습니다.
* -f {json, console}, --format {json, console}
** 기본값 : console
** 출력 결과의 포맷을 설정할 수 있습니다.

=== *COMMAND* + 
*모든 명령어는 help 옵션을 사용할 수 있습니다.* + 
 
- `*archive-wal SERVER_NAME`* + 
** archive_command나 streaming replication을 통해 들어오는 WAL 파일을 수집해서 커맨드를 실행한 서버의 WAL archive로 옮깁니다. +
** 필요한 경우 WAL파일을 압축할 수 있습니다.. 
  
- `*backup SERVER_NAME`* +
설정 파일을 기준으로 backup 작업을 수행 합니다. +
** --immediate-checkpoint
*** 강제로 checkpoint를 가능한 빠르게 즉시 수행 합니다.  
*** Config 파일의 immediate_checkpoint 설정이 무시되고, 이 옵션이 적용 됩니다.

** --no-immediate-checkpoint
*** 강제로 checkpoint 작업을 기다리지 않고 백업을 진행 합니다.

** --reuse-backup [INCREMENTAL_TYPE] + 
*** 기본값 : link
*** off : 증분 백업을 사용하지 않습니다. + 
*** copy : 변경되지 않은 파일에 대해서 복사를 하는 방식으로 백업본을 재사용 합니다. (백업에 걸리는 시간이 단축 됩니다.) + 
*** link : 변경되지 않은 파일에 대해서 Hard link를 연결하는 방식으로 백업본을 재사용 합니다. (백업 에 걸리는 시간과 공간을 줄여줍니다) + 
**** *OS에서 Hard link를 지원해야 합니다.* +

** --retry-times
*** 백업 및 복구에 실패해서 에러가 발생했을 때, 재시도할 횟수를 지정하는 옵션 입니다..
*** Config파일의 basebackup_retry_times 설정이 무시되고, 이 옵션이 적용 됩니다.

** --no-retry
*** --retry-times 0과 같은 동작을 합니다.

** --retry-sleep
*** 재시도 간의 시간 간격을 설정 합니다.
*** Config 파일의 basebackup_retry_times 설정이 무시되고, 이 옵션이 적용 됩니다.

** -j, --jobs
*** 백업 진행중 파일을 복사하는데 사용할 parallel worker의 수를 지정 합니다.
*** Config 파일의 parallel_jobs 설정이 무시되고, 이 옵션이 적용 됩니다.

** --bwlimit KBPS
*** 최대 전송 속도를 제한하는데 사용 됩니다.
*** 0으로 설정시 속도를 제한하지 않습니다.
*** 단위 : KB/s
*** Config 파일의 bandwith_limit 설정이 무시되고 이 옵션이 적용 됩니다.

** -w, --wait
*** 백업에 필요한 모든 WAL 파일이 아카이브 될 때 까지 기다립니다.

** --wait-timeout
*** -w, --wait 옵션 사용시, 기다리는 최대 시간을 설정 합니다.
*** 단위 : 초

- `*check-backup SERVER_NAME BACKUP_ID`* +
** 물리적 백업(Full backup의 시작부터 끝 까지)의 일관성을 확인하는데 필요한 모든 WAL 파일이 정상적으로 아카이브 되었는지 확인 합니다. +
** 이 커맨드는 cron 커맨드를 사용하여 백업이 실행될 때 마다 자동으로 호출되어 실행 됩니다.

- `*check-wal-archive SERVER_NAME`* +
새로운 PostgreSQL 클러스터(SERVER_NAME)에 사용할 저장소가 사용 가능한 상태인지 체크 합니다. +
추가 옵션인 타임라인을 주지 않을 경우에 저장소가 비어있어야 검사가 통과 됩니다. + 
** --timeline [TIMELINE]
*** 저장소가 사용 가능한 상태인지 체크하기 위해서, 해당 타임라인과 같거나 큰 WAL 파일이 있는지 체크 합니다. 
*** 같거나 큰 값을 가지는 WAL 파일이 있을 경우 검사에 실패 합니다.

- `*check SERVER_NAME`* + 
** 서버에 대한 특수 정보들(아래 목록)을 보여 줍니다. +
*** SSH connection check
*** PostgreSQL version
*** Configuration
*** Backup directories
*** Archiving process
*** Streaming process
*** Replication slots
** SERVER_NAME 대신에 all을 입력할 경우 모든 서버에 대해서 특수 정보들을 보여 줍니다. +
** --nagios + 
*** Nagios 플러그인에 호환 가능하도록 출력 합니다. + 

- `*cron`* +
** 보존 정책 수행 또는 WAL 파일 관리와 같은 유지 관리 작업을 수행 합니다. + 
** --keep-descriptors
*** cron 프로세스에 연결된 barman의 하위프로세스가 stdout과 stderr를 스트림 합니다.
*** Docker 기반 설치에 유용한 옵션 입니다.

- `*delete SERVER_NAME BACKUP_ID`* +
** 특정 서버의 특정 시점의 백업을 삭제 합니다. +
** BACKUP_ID는 원하는 백업의 ID를 입력할 수도 있고, 아래의 예약어도 사용 가능 합니다.
*** first : 가장 오래된 사용 가능한 백업 입니다.
*** last : 가장 최신의 사용 가능한 백업 입니다.
*** latest : last와 같습니다.
*** oldest : first와 같습니다.
*** last-failed : 가장 마지막으로 실패한 백업 입니다.

- `*diagnose`* +
** barman이 설치된 서버 및 구성된 모든 서버에 대한 아래의 진단 정보들을 수집 합니다. +
*** Global configuration
*** SSH version
*** Python version
*** rsync version
*** 모든 서버의 현재 설정 값과 상태  

- `*get-wal [OPTIONS] SERVER_NAME WAL_NAME`* +
** SERVER_NAME 서버의 WAL 아카이브에서 WAL_NAME으로 WAL파일을 검색 합니다. +
** 검색 요청한 WAL 파일을 발견하면, 압축이 되지 않은 형태로 STDOUT 출력을 해줍니다.
** 아래의 옵션들을 통해서 출력 및 실행 결과를 변경할 수  있습니다. 

*** -o OUTPUT_DIRECTORY
**** get-wal 커맨드를 통해 가져온 WAL 파일을 저장할 디렉토리 임.

*** -P, --partial
**** .partial 확장자를 가지는 불완전한 WAL 파일도 검색 합니다.

*** -z
**** 출력이 gzip을 통해서 압축된 형태로 제공됩니다.

*** -j
**** 출력이 bzip2을 통해서 압축된 형태로 제공됩니다.

*** -p SIZE
**** 요청한 WAL_NAME 파일(해당 WAL 파일의 시작지점이 0)부터 시작해서, 입력한 SIZE에 해당하는 WAL 파일까지 확인 합니다.
**** 이 옵션을 사용하면, get-wal은 행당 하나씩 zero to 'SIZE' WAL segment 이름 형태로 리스트를 반환 합니다.
**** SIZE는 정수이며, 음의 정수를 입력할 수 없습니다.

*** -t, --test
**** Barman 서버에서 WAL 검색을 위해 요청한 PostgreSQL 서버의 연결과 구성을 모두 테스트  합니다.
**** 이 옵션을 사용하면, WAL_NAME 파라미터 값이 무시됩니다.

- `*keep SERVER_NAME BACKUP_ID`* +
** SERVER_NAME 서버의 BACUKUP_ID에 해당하는 백업본의 플래그 값을 영구 보관으로 변경 합니다. +
** 보존 정책에 상관 없이 영구적으로 보관됩니다. 
** BACKUP_ID는 원하는 백업의 ID를 입력할 수도 있고, 아래의 예약어도 사용 가능 합니다.
*** first : 가장 오래된 사용 가능한 백업 입니다.
*** last : 가장 최신의 사용 가능한 백업 입니다.
*** latest : last와 같습니다.
*** oldest : first와 같습니다.
*** last-failed : 가장 마지막으로 실패한 백업 입니다. + 

** --target RECOVERY_TARGET + 
*** 영구 보관할 백업의 복구 목표를 설정할 수 있습니다. + 
*** RECOVERY_TARGET은 아래와 같은 값을 가질 수 있습니다.
**** full : 백업을 사용하여 항상 최신 시점으로 복구할 수 있습니다. 이를 위해 Barman은 백업의 WAL 일관성을 보장하기 위한 파일과 시점 복구에 필요한 WAL 파일도 같이 유지 합니다.
**** standalone : 백업을 수행한 시점의 상태로 서버를 복구하는 데만 백업을 사용할 수 있습니다. Barman은 백업의 일관성을 보장하는데 필요한 WAL 파일만 유지 합니다.

** --status
*** 해당 백업의 플래그 상태를 보고 합니다.
*** 영구 보관된 백업의 경우 full 또는 standlone 상태 값을 가지며, 영구 보관되지 않은 백업은 nokeep 상태 값을 가집니다.

** --release
*** 해당 백업의 영구 보관을 해제 합니다.
*** 영구 보관을 해제할 경우 보존 정책에 따라서 관리되어 삭제 되거나 유저가 직접 삭제할 수도  있습니다.

- `*list-backups SERVER_NAME`* + 
** SERVER_NAME 서버의 사용 가능한 백업들을 보여 줍니다. +
*** BACKUP_ID를 찾는데 유용 합니다.
*** 출력 결과 Example : servername 20111104T102647 - Fri Nov  4 10:26:48 2011 - Size: 17.0 MiB - WAL Size: 100 B
*** 이 경우에, BACKUP_ID는 20111104T102647 입니다.

- `*list-files [OPTIONS] SERVER_NAME BACKUP_ID`* +
** SERVER_NAME 서버의 BACKUP_ID에 해당하는 백업의 모든 파일을 보여 줍니다. + 
** BACKUP_ID는 원하는 백업의 ID를 입력할 수도 있고, 아래의 예약어도 사용 가능 합니다.
*** first : 가장 오래된 사용 가능한 백업 입니다.
*** last : 가장 최신의 사용 가능한 백업 입니다.
*** latest : last와 같습니다.
*** oldest : first와 같습니다.
*** last-failed : 가장 마지막으로 실패한 백업 입니다. +

** --target TARGET_TYPE
*** BACKUP_ID의 백업 파일에서 원하는 정보만 출력해 줍니다. 
*** 가능한 TYPE은 아래와 같습니다.
**** data : 데이터 파일들만 보여 줍니다.
**** standalone : 백업 파일들과 백업 일관성 유지에 필요한 WAL 파일만 보여 줍니다.
**** full : 모든 데이터 파일과 WAL 파일을 보여 줍니다.


- `*list-servers`* +
** 구성된 모든 서버와 각 서버들의 description을 출력 합니다. + 


- `*put-wal [OPTIONS] SERVER_NAME`* +
** 원격 서버(Postgres)의 WAL 파일을 Barman 백업 서버 내에 있는 SERVER_NAME 서버용 incoming 디렉토리에 안전하게 저장 합니다. + 
** WAL 파일들은 STDIN에서 검색되며, 유효성 검증을 위해 MD5SUMS 파일과 함께 tar stream으로 캡슐화 되어야 합니다.
** 이 커맨드는 barman-wal-archive 유틸리티에서 SSH를 통해 호출하기 위함 입니다.
*** barman-cli 패키지의 일부 입니다.
** 파일의 안정성을 위해서 명령어를 직접 사용하지 않는 것이 권유 됩니다.
** -t, --test
*** WAL 파일을 받을 수 있는 상태가 준비 되었는지 등 , 요청된 PostgreSQL 서버의 구성과 연결을 테스트 합니다.
  
- `*status SERVER_NAME`* +
** 해당 서버의 backups, archive_command, archive_status 등의 정보를 확인 할 수 있습니다. + 
  
  
- `*rebuild-xlogdb SERVER_NAME`* +
** SERVER_NAME 서버에 대한 WAL파일 metadata를 리빌드를 수행 합니다. +
** 모든 서버에 대해서 수행하려면 SERVER_NAME에 all을 입력 합니다. + 
** WAL 저장소에 대한 metadata는 xlog.db 파일에 저장되며, 각각의 barman 서버마다 고유의 사본을 가지고 있습니다. 

- `*receive-wal SERVER_NAME`* +
** SERVER_NAME 서버로 부터 WAL Streaming을 시작 합니다. +
** 옵션
*** --stop
**** 해당 서버와 연결된 receive-wal 프로세스를 종료 합니다.

*** --reset
**** receive-wal의 상태를 초기화 됩니다. 
**** WAL 파일 스트리밍이 재시작 됩니다.

*** --create-slot
**** 스트리밍을 위한 physical replication slot을 생성 합니다.
**** 생성될 슬롯의 이름은 Config파일의 slot_name 설정 값 입니다.

*** --drop-slot
**** physical replication slot을 삭제 합니다.
**** 삭제할 슬롯의 이름은 Config파일의 slot_name 설정 값 입니다.

- `*recover [OPTIONS] SERVER_NAME BACKUP_ID DESTINATION_DIRECTORY*` +
** BACKUP_ID의 백업으로 SERVER_NAME의 DESTINATION_DIRECTORY에 복구를 시작 합니다. +
** BACKUP_ID는 원하는 백업의 ID를 입력할 수도 있고, 아래의 예약어도 사용 가능 합니다.
*** first : 가장 오래된 사용 가능한 백업 입니다.
*** last : 가장 최신의 사용 가능한 백업 입니다.
*** latest : last와 같습니다.
*** oldest : first와 같습니다.
*** last-failed : 가장 마지막으로 실패한 백업 입니다. +
** 옵션들
*** --target-tli TARGET_TLI
**** 해당 타임라인까지 복구 합니다.

*** --target-time TARGET_TIME
**** 해당 시간까지 복구 합니다.
**** 시간 포맷 : ("YYYY-MM-DD HH:MM:SS.mmm")

*** --target-xid TARGET_XID
**** 해당 트랜잭션 ID까지 복구 합니다.

*** --target-lsn TARGET_LSN
**** 해당 LSN(Log Sequence Number)값 까지 복구 합니다.
**** PostgreSQL 10 버전 이상부터 가능 합니다.

*** --target-name TARGET_NAME
**** TARGET_NAME의 시점까지 복구 합니다.
**** 복구 시점은 pg_create_restore_point(name)을 이용해서 만들 수 있습니다.
**** PostgreSQL 9.1 버전 이상부터 가능 합니다.

*** --target-immeidate
**** 백업에 존재하는 가장 마지막 시점까지 복구 합니다.

*** --exclusive
**** 특정 target(time, XID, LSN)을 복구 대상에 포함하지 않습니다.

*** --target-action ACTION
**** target까지 복구가 완료되었을 때 수행할 액션 입니다..
**** 수행 결과에 상관 없이, 1회만 수행 됩니다.
**** target이 존재 해야 사용 가능 합니다.
**** 액션 목록
***** pause (PostgreSQL 9.1 버전 이상 지원)
***** shutdown (PostgreSQL 9.5 버전 이상 지원)
***** promote (PostgreSQL 9.5 버전 이상 지원)

*** --tablespace NAME:LOCATION
**** 테이블스페이스 재배치에 대한 룰을 설정 합니다.

*** --remote-ssh-command SSH_COMMAND
**** 원격으로 복구를 진행하는 옵션 입니다.
**** Config 파일의 ssh_command 옵션과 동일 합니다.
**** Ex) ssh postgres@tmax

*** --retry-times RETRY_TIMES
**** 백업 데이터 복사에 실패했을 때 다시 시도할 횟수를 지정 합니다.
**** Config 파일의 basebackup_retry_times의 설정 값이 무시되고, 이 설정 값이 적용 됩니다.

*** --no-retry
**** 백업 데이터 복사에 실패했을 때 다시 시도하지 않습니다.
**** --retry-times 0 과 같은 동작을 합니다.

*** --bwlimit KBPS
**** 전송 속도의 최대 속도를 제한 합니다.
**** 값이 0일 경우, 무제한 입니다.
**** Config 파일의 bandwidth_limit 설정 값이 무시되고, 이 설정 값이 적용 됩니다.

*** -j, --jobs
**** 복구 작업 중 파일 복사 시에 사용할 최대 worker의 수(병렬 처리)를 지정 합니다.
**** Config파일의 parallel_jobs 값을 무시하고 설정 됩니다.
**** Backup method를 rsync를 사용하는 서버에만 사용 가능 합니다.

*** --get-wal, --no-get-wal 
**** 복구 작업시에 WAL 파일을 가져 올지에 대한 여부를 설정 합니다.
**** Config파일의 recovery_options의 값을 무시하고 설정 됩니다.

*** --network-compression, --no-network-compression 
**** 원격 복구 작업시에 네트워크 데이터 압축을 사용할지 여부를 설정 합니다.
**** Config파일의 network_compression 값을 무시하고 설정 됩니다.

*** --standby-mode 
**** PostgreSQL 서버를 스탠바이 모드로 기동합니다.


- `*replication-status [OPTIONS] SERVER_NAME`* 
** SERVER_NAME 서버에 연결된 스트리밍 클라이언트의 실시간 정보 및 상태를 보여 줍니다.
** 아래 옵션에 따라서 다르게 동작 합니다.
** 옵션
*** --minimal
**** 기계가 읽을 수 있는 형태로 출력 합니다.

*** --target TARGET_TYPE + 
**** 기본 값 : all +  
**** TARGET_TYPE 설정 가능한 값들
***** hot-standby : hot standby 서버들만 출력 합니다.
***** wal-streamer : WAL streaming client만 출력 합니다.(pg_receivewal 같은)
***** all : 모든 스트리밍 클라이언트를 출력 합니다.

- `*show-backup SERVER_NAME BACKUP_ID`*
** SERVER_NAME 서버의 BACKUP_ID에 해당하는 백업의 자세한 정보를 보여 줍니다.
** BACKUP_ID는 원하는 백업의 ID를 입력할 수도 있고, 아래의 예약어도 사용 가능 합니다.
**** first : 가장 오래된 사용 가능한 백업 입니다.
**** last : 가장 최신의 사용 가능한 백업 입니다.
**** latest : last와 같습니다.
**** oldest : first와 같습니다.
**** last-failed : 가장 마지막으로 실패한 백업 입니다. +

** 예시 출력

----
Backup 20150828T130001:
  Server Name            : quagmire
  Status                 : DONE
  PostgreSQL Version     : 90402
  PGDATA directory       : /hypersql/pg/14.3/data

  Base backup information:
    Disk usage           : 12.4 TiB (12.4 TiB with WALs)
    Incremental size     : 4.9 TiB (-60.02%)
    Timeline             : 1
    Begin WAL            : 0000000100000CFD000000AD
    End WAL              : 0000000100000D0D00000008
    WAL number           : 3932
    WAL compression ratio: 79.51%
    Begin time           : 2015-08-28 13:00:01.633925+00:00
    End time             : 2015-08-29 10:27:06.522846+00:00
    Begin Offset         : 1575048
    End Offset           : 13853016
    Begin XLOG           : CFD/AD180888
    End XLOG             : D0D/8D36158

  WAL information:
    No of files          : 35039
    Disk usage           : 121.5 GiB
    WAL rate             : 275.50/hour
    Compression ratio    : 77.81%
    Last available       : 0000000100000D95000000E7

  Catalog information:
    Retention Policy     : not enforced
    Previous Backup      : 20150821T130001
    Next Backup          : - (this is the latest base backup)
----


- `*show-servers SERVER_NAME`*
** SERVER_NAME 서버의 자세한 정보(아래 목록)를 보여 줍니다.
*** conninfo
*** backup_directory
*** wlas_directory
*** 기타 등등
** 모든 서버에 대해서 자세한 정보를 보고 싶을 경우, SERVER_NAME에 all을 입력 합니다.

- `*status SERVER_NAME`*
** SERVER_NAME 서버의 상태 정보(아래 목록)를 보여 줍니다.
*** archive_command
*** archive_status
*** 기타 등등
** 아래는 예시 출력 입니다.

----
Server quagmire:
  Description: The Giggity database
  Passive node: False
  PostgreSQL version: 14.3
  pgespresso extension: Not available
  PostgreSQL Data directory: /hypersql/pg/14.3/data
  PostgreSQL 'archive_command' setting: rsync -a %p barman@backup:/var/lib/barman/quagmire/incoming
  Last archived WAL: 0000000100003103000000AD
  Current WAL segment: 0000000100003103000000AE
  Retention policies: enforced (mode: auto, retention: REDUNDANCY 2, WAL retention: MAIN)
  No. of available backups: 2
  First available backup: 20220908T003001
  Last available backup: 20220909T003001
  Minimum redundancy requirements: satisfied (2/1)
----

- `*switch-wal SERVER_NAME`*
** SERVER_NAME 서버에서 pg_switch_wal()을 실행하여 작성중인 WAL 파일을 새 파일로 변경 합니다.
** PostgreSQL 버전에 따라서 다르게 실행 됩니다.
*** PostgreSQL 10 버전 부터는 pg_swtich_wal()
*** PostgreSQL 8.3부터 9.6 버전 까지는 pg_switch_xlog()
** 옵션
*** --force
**** 강제로 체크포인트를 수행해서 WAL 파일을 변경 합니다.
**** 주의 : CHECKPOINT가 수행되면서 I/O 로드율이 높아질 수 있습니다.

*** --archive
**** WAL 파일이 아카이브 되는 것을 기다립니다.
**** 지정한 시간(기본 30초)동안 WAL 파일이 아카이브 되지 않을 경우 Barman이 종료 됩니다.
**** 스탠바이 서버에서 실행가능 합니다.

*** --archive-timeout TIMEOUT
**** 기본 값 : 30초
**** WAL 파일 아카이브를 기다리는 최대 시간을 지정 합니다.
**** 스탠바이 서버에서 실행 가능 합니다.

- `*switch-xlog SERVER_NAME`*
** swtich-wal의 alias이며, 똑같은 동작을 수행 합니다.

- `*sync-backup SERVER_NAME BACKUP_ID`*
** *Passive node(barman 이중화시 standby 역할의 barman)에서만 사용 가능 합니다.*
** Passive node와 Primary node의 동기화를 위해 사용 합니다.
** SERVER_NAME 서버의 BACKUP_ID에 해당하는 백업의 모든 파일을 Primary node로 부터 Passive node로 복사 합니다.
** Passive node에서 Primary node로 연결하기 위해 Config파일의 primary_ssh_command 값을 사용 합니다.

- `*sync-info SERVER_NAME [LAST_WAL[LAST_POSISION]]`*
** 동기화 목적으로 사용된 Barman 서버의 현재 상태를 수집 합니다.
** SERVER_NAME 서버에 대한 정보를 JSON 형태로 출력 합니다.
*** 성공적으로 끝난 모든 백업들
*** Archive 된 모든 WAL 파일
*** configuration
*** xlog.db 파일에 기록된 마지막 WAL 파일 및 해당 내용의 파일 내에서의 위치 입니다.

*** LAST_WAL
**** 해당 WAL 파일 이전의 파일을 건너 뜁니다. (증분 동기화)

*** LAST_POSITION
**** xlog.db 파일 내에서 빠른 위치 지정을 위한 힌트 입니다. (증분 동기화) 

- `*sync-wals SERVER_NAME`*
** *Passive node(barman 이중화시 standby 역할의 barman)에서만 사용 가능 합니다.*
** Passive node와 Primary node의 동기화를 위해 사용 됩니다.
** SERVER_NAME 서버의 아카이브 된 모든 WAL 파일을 Primary node로 부터 Passive node로 복사 합니다. 
** Passive node에서 Primary node로 연결하기 위해 Config파일의 primary_ssh_command 값을 사용 합니다. + 

== 6. 백업 및 복구 테스트
* 테스트 *

=== 4.1 barman.conf 변경
barman OS 유저, 로그 및 보존 정책등을 설정 해줍니다.

[source, sh]
----
; Barman, Backup and Recovery Manager for PostgreSQL
; http://www.pgbarman.org/ - http://www.enterprisedb.com/
;
; Main configuration file

[barman]
; System user
barman_user = barman

; Directory of configuration files. Place your sections in separate files with .conf extension
; For example place the 'main' server section in /etc/barman.d/main.conf
configuration_files_directory = /etc/barman.d

; Main directory
barman_home = /var/lib/barman

; Log location
log_file = /hypersql/pg/14/log/barman/barman.log

; Log level (see https://docs.python.org/3/library/logging.html#levels)
log_level = INFO

; Default compression level: possible values are None (default), bzip2, gzip, pigz, pygzip or pybzip2
;compression = gzip

; Global bandwidth limit in kilobytes per second - default 0 (meaning no limit)
;bandwidth_limit = 4000

; Number of parallel jobs for backup and recovery via rsync (default 1)
;parallel_jobs = 1

; Immediate checkpoint for backup command - default false
;immediate_checkpoint = false

; Enable network compression for data transfers - default false
;network_compression = false

; Number of retries of data copy during base backup after an error - default 0
;basebackup_retry_times = 0

; Number of seconds of wait after a failed copy, before retrying - default 30
;basebackup_retry_sleep = 30

; Maximum execution time, in seconds, per server
; for a barman check command - default 30
;check_timeout = 30

; Minimum number of required backups (redundancy)
;minimum_redundancy = 1

; Global retention policy (REDUNDANCY or RECOVERY WINDOW)
; Examples of retention policies
; Retention policy (disabled, default)
;retention_policy =
; Retention policy (based on redundancy)
;retention_policy = REDUNDANCY 2
; Retention policy (based on recovery window)
;retention_policy = RECOVERY WINDOW OF 4 WEEKS

----

=== 4.2 barman.d/관리서버.conf 생성
barman 서버에서 관리할 PostgreSQL 서버에 대한 정보를 저장합니다. +
아래 파일 기준 설정 값은 아래와 같습니다. + 

- incoming_wals_directory + 
** /hypersql/backup/barman/incoming_wals/hypersql

- backup_directory + 
** /hypersql/backup/barman/backup_files/hypersql

- streaming_wals_directory + 
** /hypersql/backup/barman/streaming_wals/hypersql

`vi /etc/barman.d/hypersql.conf` + 

[source, ini]
----
[hypersql]
description =  "Hypersql for PostgreSQL Server version 14"

; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; PostgreSQL connection string (mandatory)
; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
conninfo = host=172.27.0.66 user=barman dbname=postgres

; ;;;;;;;;;;;;;;;;;;;;;;;;
; SSH command
;;;;;;;;;;;;;;;;;;;;;;;;;;
ssh_command = ssh hypersql@172.27.0.66

; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; PostgreSQL streaming connection string
; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; To be used by pg_basebackup for backup and pg_receivewal for WAL streaming
; NOTE: streaming_barman is a regular user with REPLICATION privilege
streaming_conninfo = host=172.27.0.66 user=barman

; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Backup settings (via pg_basebackup)
; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
backup_method = rsync
backup_directory = /hypersql/backup/barman/backup_files/hypersql
;streaming_backup_name = barman_streaming_backup

; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; WAL streaming settings (via pg_receivewal)
; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
streaming_archiver = on
slot_name = barman_slot
create_slot = auto
streaming_archiver_name = barman_receive_wal
streaming_wals_directory = /hypersql/backup/barman/streaming_wals/hypersql


; ;;;;;;;;;;;;;;;;;;;;;;
; WAL archiving (via 'archive_command')
; ;;;;;;;;;;;;;;;;;;;;;;
archiver = true
incoming_wals_directory = /hypersql/backup/barman/incoming_wals/hypersql

; PATH setting for this server
path_prefix = "/usr/pgsql-14/bin"

----

=== 4.3 ssh-key 등록
ssh-key 생성 + 
- `ssh-keygen` + 
- barman 백업 서버 와 PostgreSQL 운영 서버 모두 생성해줘야 합니다.

ssh-key 복사 + 
생성된 barman 백업 서버의 public key를 PostgreSQL 운영 서버로 복사 해줍니다. + 
- barman 백업 서버에서 아래의 명령 실행
- `ssh-copy-id -i ~/.ssh/id_rsa.pub postgres@192.168.0.2` + 
- Are you sure you want to continue connecting (yes/no)? yes + 
 + 
마찬가지로, 생성된 PostgreSQL 운영 서버의 public key를 barman 백업 서버로 복사 해줍니다. + 
- PostgreSQL 운영 서버에서 아래의 명령 실행
- `ssh-copy-id -i ~/.ssh/id_rsa.pub barman@192.168.0.3` + 
- Are you sure you want to continue connecting (yes/no)? yes + 

ssh 접속 테스트 + 
barman 백업 서버에서 테스트 시 + 
- `ssh postgres@192.168.0.2` + 
PostgreSQL 운영 서버에서 테스트 시 + 
- `ssh barman@192.168.0.3` + 

두 접속 모두 패스워드를 묻지 않고 바로 접속이 되어야 합니다.

=== 4.4 wal 아카이브
PostgreSQL 운영 서버의 postgresql.conf를 변경 해줍니다. + 

`vi postgresql.conf` + 

[source, sh]
----
# Archiving 
# 아카이브 커맨드를 on으로 변경해줍니다.
archive_mode = on               # enables archiving; off, on, or always

# 아카이브 커맨드를 아래처럼 rsync를 이용하도록 설정 해줍니다.
archive_command = 'rsync -a %p barman@192.168.0.3:/hypersql/backup/barman/incoming_wals/hypersql/%f'
                
#archive_timeout = 0            # force a logfile segment switch after this
                                # number of seconds; 0 disables
----

barman 백업 서버에서 환경 구성 상태를 체크합니다. + 
`barman check 서버명`

[source, sh]
----
[barman@Barman-4C8G:~]$ barman check 서버명
Server hypersql:
        PostgreSQL: OK
        superuser or standard user with backup privileges: OK
        PostgreSQL streaming: OK
        wal_level: OK
        replication slot: OK
        directories: OK
        retention policy settings: OK
        backup maximum age: OK (no last_backup_maximum_age provided)
        backup minimum size: OK (0 B)
        wal maximum age: OK (no last_wal_maximum_age provided)
        wal size: OK (0 B)
        compression settings: OK
        failed backups: OK (there are 0 failed backups)
        minimum redundancy requirements: OK (have 0 backups, expected at least 0)
        ssh: OK (PostgreSQL server)
        not in recovery: OK
        systemid coherence: OK (no system Id stored on disk)
        pg_receivexlog: OK
        pg_receivexlog compatible: OK
        receive-wal running: OK
        archive_mode: OK
        archive_command: OK
        continuous archiving: OK
        archiver errors: OK
----

continous archiving 에러가 발생할 경우, 아래의 명령어를 실행합니다. + 
`barman switch-xlog 서버명 `
`barman cron 서버명`

=== 4.5 wal 스트리밍
설정 파일 구성 후에, `barman cron 서버명` 명령어를 실행하게 되면, 자동으로 스트리밍이 시작됩니다.

=== 4.6 풀백업
`barman backup 서버명` 명령어를 이용해 백업합니다.

[source,sh]
----
[barman@Barman-4C8G:~]$ barman backup hypersql
Starting backup using rsync-exclusive method for server hypersql in /hypersql/backup/barman/backup_files/hypersql/base/20220622T134916
Backup start at LSN: 0/3D000028 (00000001000000000000003D, 00000028)
This is the first backup for server hypersql
WAL segments preceding the current backup have been found:
        00000001000000000000003B from server hypersql has been removed
Starting backup copy via rsync/SSH for 20220622T134916
Copy done (time: 2 seconds)
This is the first backup for server hypersql
Asking PostgreSQL server to finalize the backup.
Backup size: 116.6 MiB
Backup end at LSN: 0/3D000138 (00000001000000000000003D, 00000138)
Backup completed (start time: 2022-06-22 13:49:17.025155, elapsed time: 4 seconds)
Processing xlog segments from streaming for hypersql
        00000001000000000000003C
        00000001000000000000003D
Processing xlog segments from file archival for hypersql
        00000001000000000000003C
        00000001000000000000003D
        00000001000000000000003D.00000028.backup

# 백업 파일 디렉토리 확인
[barman@Barman-4C8G:/hypersql/backup/barman/backup_files/hypersql]$ ls -lah
total 4.0K
drwxrwxr-x 5 barman barman 65 Jun 22 13:49 .
drwxrwxr-x 4 barman barman 36 Jun 22 10:51 ..
drwxrwxr-x 3 barman barman 29 Jun 22 13:49 base
drwxrwxr-x 2 barman barman  6 Jun 22 10:56 errors
-rw-rw-r-- 1 barman barman 64 Jun 22 13:49 identity.json
drwxrwxr-x 3 barman barman 45 Jun 22 13:49 wals

# 백업 파일 생성 확인
[barman@Barman-4C8G:/hypersql/backup/barman/backup_files/hypersql/base]$ ls -lah
total 0
drwxrwxr-x 3 barman barman 29 Jun 22 13:49 .
drwxrwxr-x 5 barman barman 65 Jun 22 13:49 ..
drwxrwxr-x 4 barman barman 50 Jun 22 13:49 20220622T134916

# 테이블스페이스 및 데이터 디렉토리가 정상적으로 백업 된 것을 확인
[barman@Barman-4C8G:/hypersql/backup/barman/backup_files/hypersql/base/20220622T134916]$ ls -lah
total 8.0K
drwxrwxr-x  4 barman barman   50 Jun 22 13:49 .
drwxrwxr-x  3 barman barman   29 Jun 22 13:49 ..
drwx------  3 barman barman   29 Jun 13 16:45 24733
-rw-rw-r--  1 barman barman 1.1K Jun 22 13:49 backup.info
drwx------ 21 barman barman 4.0K Jun 22 13:49 data

#barman 명령어를 통해서 백업 상태 확인
[barman@Barman-4C8G:/hypersql/backup/barman/backup_files/hypersql/base]$ barman show-backup hypersql 20220622T134916
Backup 20220622T134916:
  Server Name            : hypersql
  System Id              : 7099021779009251294
  Status                 : DONE
  PostgreSQL Version     : 140002
  PGDATA directory       : /hypersql/pg/data
  Tablespaces:
    tblspc_01: /hypersql/pg/tblspc (oid: 24733)

  Base backup information:
    Disk usage           : 116.6 MiB (132.6 MiB with WALs)
    Incremental size     : 116.6 MiB (-0.00%)
    Timeline             : 1
    Begin WAL            : 00000001000000000000003D
    End WAL              : 00000001000000000000003D
    WAL number           : 1
    Begin time           : 2022-06-22 13:49:16.933814+09:00
    End time             : 2022-06-22 13:49:20.682264+09:00
    Copy time            : 2 seconds
    Estimated throughput : 41.3 MiB/s
    Begin Offset         : 40
    End Offset           : 312
    Begin LSN           : 0/3D000028
    End LSN             : 0/3D000138

  WAL information:
    No of files          : 0
    Disk usage           : 0 B
    Last available       : 00000001000000000000003D

  Catalog information:
    Retention Policy     : not enforced
    Previous Backup      : - (this is the oldest base backup)
    Next Backup          : - (this is the latest base backup)

----

=== 4.7 증분백업
[source, sql]
----
# PostgreSQL 서버에서 데이터를 임의의 데이터 변경 후에 증분백업 실시
postgres=# UPDATE one SET first_name='incremental_test' where id=1;
UPDATE 1
postgres=# CHECKPOINT;
CHECKPOINT
----

[source, sh]
----
[barman@Barman-4C8G:/hypersql/backup/barman/backup_files/hypersql/base]$ barman backup --reuse=link hypersql
Starting backup using rsync-exclusive method for server hypersql in /hypersql/backup/barman/backup_files/hypersql/base/20220622T140155
Backup start at LSN: 0/3F000028 (00000001000000000000003F, 00000028)
Starting backup copy via rsync/SSH for 20220622T140155
Copy done (time: less than one second)
Asking PostgreSQL server to finalize the backup.
Backup size: 116.6 MiB. Actual size on disk: 488.9 KiB (-99.59% deduplication ratio).
Backup end at LSN: 0/3F000100 (00000001000000000000003F, 00000100)
Backup completed (start time: 2022-06-22 14:01:55.969396, elapsed time: 2 seconds)
Processing xlog segments from streaming for hypersql
        00000001000000000000003E
Processing xlog segments from file archival for hypersql
        00000001000000000000003E
        00000001000000000000003F
        00000001000000000000003F.00000028.backup



[barman@Barman-4C8G:/hypersql/backup/barman/backup_files/hypersql/base]$ barman list-backup hypersql
WARNING: No backup strategy set for server 'hypersql' (using default 'exclusive_backup').
WARNING: The default backup strategy will change to 'concurrent_backup' in the future. Explicitly set 'backup_options' to silence this warning.
hypersql 20220622T140155 - Wed Jun 22 14:01:57 2022 - Size: 132.6 MiB - WAL Size: 0 B (tablespaces: tblspc_01:/hypersql/pg/tblspc)
hypersql 20220622T134916 - Wed Jun 22 13:49:20 2022 - Size: 132.6 MiB - WAL Size: 32.0 MiB (tablespaces: tblspc_01:/hypersql/pg/tblspc)        
----

=== 4.8 복원 및 복구
위에서 생성한 백업 파일을 이용해서 복원 및 복구하는 방법 +
테스트이므로 기존 디렉토리가 아닌 다른 디렉토리에 복원 및 복구를 진행 하겠습니다. + 
 + 

*복원 및 복구 시의 주의해야 할 점으로, archive_command가 false로 초기화 되기 때문에, 설정을 변경 후에 기동해야 합니다.* + 

백업 서버에서 SSH를 통해 원격 복구를 진행하겠습니다. + 
`barman recover --target-immediate --remote-ssh 'ssh postgres@192.168.0.2' hypersql latest /hypersql/recover/`

[source,sh]
----
[barman@Barman-4C8G:/hypersql/backup/barman/backup_files/hypersql/base]$ barman recover --target-immediate --remote-ssh-command 'ssh postgres@172.27.0.251' hypersql latest /hypersql/recover
WARNING: No backup strategy set for server 'hypersql' (using default 'exclusive_backup').
WARNING: The default backup strategy will change to 'concurrent_backup' in the future. Explicitly set 'backup_options' to silence this warning.
Starting remote restore for server hypersql using backup 20220622T140155
Destination directory: /hypersql/recover
Remote command: ssh postgres@192.168.0.2
Doing PITR. Recovery target immediate: True
        24733, tblspc_01, /hypersql/pg/tblspc
Copying the base backup.
Copying required WAL segments.
Generating recovery configuration
Identify dangerous settings in destination directory.

IMPORTANT
These settings have been modified to prevent data losses

postgresql.conf line 246: archive_command = false

Recovery completed (start time: 2022-06-22 14:35:58.105236, elapsed time: 7 seconds)

Your PostgreSQL server has been successfully prepared for recovery!
----

PostgreSQL운영 서버에 접속하여, PostgreSQL 서버를 기동 시키고 first_name을 incremental_test로 변경한 데이터가 존재하는지 확인합니다. + 

[source, sh]
----
[postgres@HW-2-4C8G:~/recover]$ pg_ctl start -D /hypersql/recover/
waiting for server to start....2022-06-24 15:28:25.372 KST [1019] LOG:  redirecting log output to logging collector process
2022-06-24 15:28:25.372 KST [1019] HINT:  Future log output will appear in directory "log".
 done
server started

[postgres@HW-2-4C8G:~/recover]$ psql
psql (14.2)
Type "help" for help

postgres=# SELECT * FROM one where id=1;
 id |    first_name    | last_name |       email        | gender |   ip_address   |                               info
                           |          en_first_name
----+------------------+-----------+--------------------+--------+----------------+---------------------------------------
---------------------------+----------------------------------
  1 | incremental_test | Beales    | kbeales0@nifty.com | Female | 140.139.182.23 | {"name":"추다진","age":"1","Product":{
"pens":1495,"notes":2328}} | 69b40fb60ccb4ad4f781e48130cf6734
(1 row)
----