= oracle_fdw
:toc:
:toc-title: 목차

== 1. 문단제목나중에정함
DB Link와 동일 기능이나, 스키마(PostgreSQL에서는 데이터베이스)단위로 연결하는 것이 아니라 해당 스키마의 한 테이블 단위로 연결 가능.

== 2. 설치
=== 2.1 설치 요구사항
모두 PostgreSQL Server에 설치 + 
 + 
PostgreSQL Version : 9.3 이상 +
    - 9.6.0 ~ 9.6.8과 10.0 ~ 10.3은 API 이슈로 인해 지원되지 않음 + 
Oracle Version : 11.2 ~ 21

[width 500%, options=header]
|===
|요구 라이브러리 | 설명
|postgresql14-devel | PostgreSQL Repository에서 받을 수 있으며, PostgreSQL 버전과 동일 버전이 필요.
|oracle-instantclient18.5-basic | Oralce 홈페이지에서 받을 수 있으며, 오라클과 동일 버전이 필요.
|oracle-instantclient18.5-devel | Oralce 홈페이지에서 받을 수 있으며, 오라클과 동일 버전이 필요.
|===

==== 주의사항
LDAP 라이브러리가 Oracle Client에 들어있으며, PostgreSQL의 라이브러리와 충돌이 발생할 수 있음. +
따라서 PostgreSQL을 Compile할 때, `--without-ladp` 옵션을 주기를 권고하고 있음. + 
 + 
추가적인 발견된 이슈사항은 아래의 링크 참고 + 
`https://github.com/laurenz/oracle_fdw#8-problems`

=== 2.2 Install on Linux
==== 설치환경
PostgreSQL Server + 

|=======
| OS | CentOS 7.6
| PostgreSQL Version | PostgreSQL 14.2
| .NET core version | 6.0
|=======
  
Oracle Server
 
|=======
| OS | CentOS 7.6
| Oracle Version | 18.4
|=======


==== 2.2.1 Oracle instantClient 다운로드
`wget https://download.oracle.com/otn_software/linux/instantclient/185000/oracle-instantclient18.5-basic-18.5.0.0.0-3.x86_64.rpm` + 
`wget https://download.oracle.com/otn_software/linux/instantclient/185000/oracle-instantclient18.5-devel-18.5.0.0.0-3.x86_64.rpm` + 

==== 2.2.2 rpm 설치
`rpm -ivh oracle-instantclient18.5-basic-18.5.0.0.0-3.x86_64.rpm`
`rpm -ivh oracle-instantclient18.5-devel-18.5.0.0.0-3.x86_64.rpm`

==== 2.2.3 환경변수 추가
`vi ~/.bash_profile` + 
[source, sh]
----
# 본인의 PostgreSQL 버전 및 연결하고자 하는 Oracle 버전에 맞는 lib 디렉토리 설정
 LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/pgsql-14/lib/:/etc:/usr/include/oracle/18.5/client64:/usr/lib/or acle/18.5/client64/lib
----
`source ~/.bash_profile` + 

==== 2.2.4 oracle_fdw 다운로드 및 설치
`wget https://github.com/laurenz/oracle_fdw/archive/refs/tags/ORACLE_FDW_2_4_0.tar.gz` + 
`tar xvzf ORACLE_FDW_2_4_0.tar.gz` + 
`cd ORACLE_FDW_2_4_0` + 
`make & make install`

=== 2.3 Install on Windows
PostgreSQL Server
|=======
| OS | Windows 10 21H2
| PostgreSQL Version | PostgreSQL 14.2
| .NET core version | 6.0
|=======
 
Oracle Server
 
|=======
| OS | CentOS 7.6
| Oracle Version | 18.4
|=======


== 3. 테스트

=== 3.1 Test on Linux
==== 3.1.2 EXTENSION 생성
postgres(superuser)로 psql 접속 + 

[source, SQL]
----
postgres=# CREATE EXTENSION oracle_fdw;
CREATE EXTENSION
---- 

==== 3.1.2 SERVER 생성
[source, SQL]
----
--서버명, 오라클 호스트/서비스명 수정해서 사용
postgres=# CREATE SERVER oradb FOREIGN DATA WRAPPER oracle_fdw OPTIONS(dbserver '//192.168.173.166:1539/XE'); ;
CREATE SERVER
---- 

==== 3.1.2 SERVER 권한 주기
[source, SQL]
----
--서버명, 유저명 수정해서 사용
postgres=# GRANT USAGE ON FOREIGN SERVER oradb TO postgres;
GRANT
---- 

==== 3.1.3 SERVER 접속 유저 설정
[source, SQL]
----
--권한을 받을 PostgreSQL유저명, 서버명, 오라클 유저명 수정해서 사용
postgres=# CREATE USER MAPPING FOR tmax SERVER oradb OPTIONS (user 'tmax', password '1234');
CREATE USER MAPPING
---- 

==== 3.1.4 FOREIGN TABLE 생성
[source, SQL]
----
--오라클의 기존 스키마를 확인 후에 수정해서 사용
--주의 사항으로는, 스키마명, 테이블명 모두 대문자로 적어야함
--추가적으로, PrimaryKey를 지정해야 UPDATE, DELETE가 가능함. INSERT는 그냥 가능함.
postgres=# CREATE FOREIGN TABLE oratest (
id integer,
text varchar(30))
SERVER oradb OPTIONS (schema 'TMAX', table 'TEST');
CREATE FOREIGN TABLE

--id가 primary key라면 아래처럼 변경하여 생성
id integer OPTIONS (key 'true')  NOT NULL
---- 

==== 3.1.5 연동 테스트
----
postgres=# SELECT * FROM oratest;
 id |    text
----+------------
  1 | test123123
  2 | 2test2
  3 | 3test2
(3 rows)

postgres=# INSERT INTO oratest VALUES(4, 'test33');
INSERT 0 1

postgres=# SELECT * FROM oratest;
 id |    text
----+------------
  1 | test123123
  2 | 2test2
  3 | 3test2
  4 | test33
(4 rows)
----

=== 3.2 Test on Windows
