= pg_stat_statements extention
:toc:
:toc-title:
:table-caption!:
:sectnums:

git 주소 : https://github.com/postgres/postgres/tree/master/contrib/pg_stat_statements
postgresql 공식 문서 : https://www.postgresql.org/docs/current/pgstatstatements.html

== pg_stat_statements 란?
서버에서 실행되었던 쿼리들에 대한 실행 통계 정보를 보여줍니다. 해당 쿼리 실행 통계정보는 `pg_stat_statements` view로 제공됩니다.

== 설치
HyperSQL은 기본적으로 contrib 모듈을 설치합니다. contrib 패키지가 설치되어 있지 않다면 설치 후 진행합니다.

- shared_preload_libraries 추가
[source,bash]
vi postgresql.conf
shared_preload_libraries = 'pg_stat_statements'

- PostgreSQL 서버 재시작
[source,bash]
pg_ctl restart

- Extension 추가
[source,sql]
create extension pg_stat_statement;

== 함수
* *pg_stat_statements_reset() returns void* +
** pg_stat_statements에서 사용하기 위해 수집된 모든 정보를 삭제합니다.
** 실행 권한 : superuser

* *pg_stat_statements(showtext boolean) returns setof record*
** `pg_stat_statements` view의 정보를 함수로도 조회가 가능합니다. `showtext := false` 로 설정하면 쿼리의 내용을 조회하지 않고 출력합니다. 해당 함수를 이용하면 예측할 수 없는 쿼리의 길이를 출력하여 생기는 오버헤드에 대한 부담을 줄일 수 있습니다.

== 파라미터
postgresql.conf에 사용되는 파라미터는 다음과 같습니다.

* *pg_stat_statemetns.max (integer)*
** pg_stat_statements에서 처리하는 쿼리의 최대수를 지정합니다. 해당 파라미터를 넘게 되면 제일 마지막에 실행된 쿼리가 삭제됩니다.
** default = 1000
** 변경 시 서버 재시작 필요

* *pg_stat_statements.track (enum)*
** 수집할 쿼리문의 사용빈도에 따른 쿼리문 사용 통계 정보 수집범위를 지정합니다. `top` 은 자주 사용되는 쿼리를 대상으로 하고, `all` 은 모든 쿼리들을 대상으로, `none` 으로 지정하면 어떤 쿼리도 수집하지 않습니다.
** default = top
** 변경 권한 : superuser
** 동적으로 변경 가능

* *pg_stat_statements.track_utility (boolean)*
** SELECT, INSERT, UPDATE, DELETE 구문 외에 다른 구문들도 수집 대상으로 포함시킬 지 지정합니다.
** default = on
** 변경 권한 : superuser
** 동적으로 변경 가능 

* *pg_stat_statements.save (boolean)*
** 서버가 중지되고 재실행되었을 때 마지막 중지 시점의 쿼리문 통계정보를 저장할 것인지를 지정합니다. off로 설정하면, 서버가 재실행될 때 모든 쿼리문에 대한 통계정보를 초기화 합니다.
** default = on
** 변경은 postgresql.conf 에서나 실행 시 파라미터 옵션으로만 설정 가능

== pg_stat_statements view
해당 뷰에서 `queryid` 는 SuperUser 또는 해당 구성원만 조회할 수 있습니다.

`pg_stat_statements` view에서 상수부분에 $1로 표시된 것은 동일한 쿼리에서 상수 값만 변경된 형태입니다.

사용자는 queryid를 dbid와 userid가 결합된 형태로 사용하고 싶을 수도 있습니다. 하지만 해시값의 안정성에 대한 보장을 할 수 없습니다. 그리고 이 식별자는 analyze 후 tree에서 파생되는 값이기 때문에 내부 객체 식별자의 함수입니다. 그렇기 때문에 플랫폼이나 기계적 아키텍쳐가 다른 경우에는 해싱 프로세스가 다른 해시값을 도출하게 됩니다. 

queryid가 안정성이 있다고 얘기할 수 있는 것은 서버의 버전과 catalog metata와 같은 경우에 hash값이 같아야 완전히 같다고 가정할 수 있어야 합니다. 물리적인 WAL replication을 통한 두 서버는 쿼리에 대한 동일한 값을 가질 것으로 예상할 수 있습니다. 하지만 logical replication 구조에서는 각종 세부사항에 대해서 동일하지 않기 때문에 queryid는 같은 식별자가 될 수 없습니다.

plan과 calls에 대한 데이터는 단계가 성공적인 작업에 대해서만 기록되기 때문에 항상 일치하지 않을 수 있습니다. 예를 들어 성공적으로 쿼리문에 대해 plan을 세웠지만 해당 쿼리를 실행하는 중에 오류가 발생하면 calls는 count되지 않습니다.

NOTE: `queryid` 의 값은 `compute_query_id` 파라미터가 활성화되어 있어야 합니다.

- postgresql v13 이상 +
View "public.pg_stat_statements"

       Column        |       Type       | Comments 
---------------------+------------------+--------------------------------
 userid              | oid              | 해당 쿼리를 실행했던 사용자의 OID
 dbid                | oid              | 해당 쿼리를 실행했던 데이터베이스 OID
 toplevel            | boolean          | 
 queryid             | bigint           | internal hash code, 구문의 계산된 parse tree 
 query               | text             | 해당 쿼리 내용(track_activity_query_size 값으로 지정한 크기만큼만 저장됨)
 plans               | bigint           | 쿼리문이 계획된 횟수
 total_plan_time     | double precision | 쿼리문 계획에 소요된 총 시간(ms)
 min_plan_time       | double precision | 쿼리문 계획에 소요된 최소 시간(ms)
 max_plan_time       | double precision | 쿼리문 계획에 소요된 최대 시간(ms)
 mean_plan_time      | double precision | 쿼리문 계획에 소요된 평균 시간(ms)
 stddev_plan_time    | double precision | 쿼리문 계획에 소요된 시간의 표준 편차(ms)
 calls               | bigint           | 쿼리문이 실행된 횟수
 total_exec_time     | double precision | 쿼리문의 총 실행 시간 (ms)
 min_exec_time       | double precision | 쿼리문 실행에 소요된 최소 시간(ms)
 max_exec_time       | double precision | 쿼리문 실행에 소요된 최대 시간(ms)
 mean_exec_time      | double precision | 쿼리문 실행에 소요된 평균 시간(ms)
 stddev_exec_time    | double precision | 쿼리문 실행에 소요된 시간의 표준 편차(ms)
 rows                | bigint           | 쿼리문에 의해 검색되거나 영향을 받는 총 행수
 shared_blks_hit     | bigint           | 쿼리문에 의한 총 공유 블록 캐시 적중 수
 shared_blks_read    | bigint           | 쿼리문이 읽은 총 공유 블록 수
 shared_blks_dirtied | bigint           | 쿼리문에 의해 dirty 블록이 된 수
 shared_blks_written | bigint           | 쿼리문이 작성한 총 공유 블록 수
 local_blks_hit      | bigint           | 쿼리문에 의한 총 로컬 블록 캐시 적중 수
 local_blks_read     | bigint           | 쿼리문이 읽은 총 로컬 블록 수
 local_blks_dirtied  | bigint           | 쿼리문에 의해 로컬 dirty 블록이 된 수
 local_blks_written  | bigint           | 쿼리문이 작성한 총 로컬 블록 수
 temp_blks_read      | bigint           | 쿼리문이 읽은 총 임시 블록 수
 temp_blks_written   | bigint           | 쿼리문이 작성한 총 임시 블록 수
 blk_read_time       | double precision | 쿼리문이 블록을 읽을 때 소요한 총 시간(ms)
 blk_write_time      | double precision | 쿼리문이 블록을 쓸 때 소요한 총 시간(ms)
 wal_records         | bigint           | 쿼리문에 의해 생성된 총 WAL 레코드 수
 wal_fpi             | bigint           | 쿼리문에 의해 생성된 WAL 전체 페이지 이미지의 총 수
 wal_bytes           | numeric          | 쿼리문에 의해 생성된 WAL의 총량(byte)



- postgresql v12 이하 +
View "public.pg_stat_statements

       Column        |       Type       | Comments
---------------------+------------------+--------------------------------
 userid              | oid              | 해당 쿼리를 실행했던 사용자의 OID
 dbid                | oid              | 해당 쿼리를 실행했던 데이터베이스 OID
 queryid             | bigint           | internal hash code, 구문의 계산된 parse tree
 query               | text             | 해당 쿼리 내용
 calls               | bigint           | 쿼리문이 실행된 횟수
 total_time          | double precision | 쿼리문의 총 실행 시간 (ms)
 min_time            | double precision | 쿼리문 실행에 소요된 최소 시간(ms)
 max_time            | double precision | 쿼리문 실행에 소요된 최대 시간(ms)
 mean_time           | double precision | 쿼리문 실행에 소요된 평균 시간(ms)
 stddev_time         | double precision | 쿼리문 실행에 소요된 평균 시간(ms)
 rows                | bigint           | 쿼리문에 의해 검색되거나 영향을 받는 총 행수
 shared_blks_hit     | bigint           | 쿼리문에 의한 총 공유 블록 캐시 적중 수
 shared_blks_read    | bigint           | 쿼리문이 읽은 총 공유 블록 수
 shared_blks_dirtied | bigint           | 쿼리문에 의해 dirty 블록이 된 수
 shared_blks_written | bigint           | 쿼리문이 작성한 총 공유 블록 수
 local_blks_hit      | bigint           | 쿼리문에 의한 총 로컬 블록 캐시 적중 수
 local_blks_read     | bigint           | 쿼리문이 읽은 총 로컬 블록 수
 local_blks_dirtied  | bigint           | 쿼리문에 의해 로컬 dirty 블록이 된 수
 local_blks_written  | bigint           | 쿼리문이 작성한 총 로컬 블록 수
 temp_blks_read      | bigint           | 쿼리문이 읽은 총 임시 블록 수
 temp_blks_written   | bigint           | 쿼리문이 작성한 총 임시 블록 수
 blk_read_time       | double precision | 쿼리문이 블록을 읽을 때 소요한 총 시간(ms)
 blk_write_time      | double precision | 쿼리문이 블록을 쓸 때 소요한 총 시간(ms)


== 테스트

--------------
postgres=# select pg_stat_statements_reset();

$ pgbench -i -s 1
$ pgbench -c 10 -t 300

postgres=# postgres=# SELECT query, calls, total_exec_time, rows, 100.0 * shared_blks_hit / nullif(shared_blks_hit + shared_blks_read, 0) AS hit_percent FROM pg_stat_statements ORDER BY total_exec_time DESC LIMIT 5;
                                query                                | calls |  total_exec_time   |  rows  |     hit_percent      
---------------------------------------------------------------------+-------+--------------------+--------+----------------------
 UPDATE pgbench_branches SET bbalance = bbalance + $1 WHERE bid = $2 |  3000 |  9825.648093000027 |   3000 |  99.9982651839772392
 UPDATE pgbench_tellers SET tbalance = tbalance + $1 WHERE tid = $2  |  3000 |  7448.384336000014 |   3000 |  99.9966524955645566
 UPDATE pgbench_accounts SET abalance = abalance + $1 WHERE aid = $2 |  3000 | 106.78840300000023 |   3000 |  98.7657091561938959
 copy pgbench_accounts from stdin                                    |     1 |          81.206247 | 100000 | 100.0000000000000000
 vacuum analyze pgbench_accounts                                     |     1 |          52.918577 |      0 |  99.9202710783336655
(5 rows)
--------------