
= pg_dumpall
:toc: 
:toc-title: 목차
:sectlinks:

== 1. pg_dumpall 란?
- 공식 문서 참고 : https://www.postgresql.org/docs/current/app-pg-dumpall.html

pg_dumpall 은 전체 클러스터의 모든 PostgreSQL 데이터베이스를 하나의 스크립트 파일로 덤프하고 백업하기 위한 유틸리티입니다. 
스크립트 파일에는 데이터베이스를 복원하기 위해 psql 에 대한 입력으로 사용할 수 있는 SQL 명령이 포함되어 있습니다.


pg_dumpall 은 내부적으로 pg_dump 를 호출 하므로 일부 메시지는 pg_dump 를 참조합니다.

덤프 스크립트가 오류 없이 완전히 실행될 것으로 기대해서는 안 됩니다. 특히 스크립트는 CREATE ROLE소스 클러스터에 존재하는 모든 역할에 대해 발행하기 때문에 대상 클러스터가 다른 부트스트랩 수퍼유저 이름으로 초기화되지 않는 한 부트스트랩 수퍼유저에 대해 " 역할이 이미 존재합니다 " 오류가 발생하는 것은 확실합니다. 이 오류는 무해하며 무시해야 합니다. 

pg_dumpall 은 복원 전에 필요한 모든 테이블스페이스 디렉토리가 있어야 합니다. 그렇지 않으면 기본 위치가 아닌 데이터베이스에 대한 데이터베이스 생성이 실패합니다.

== 2. pg_dumpall 옵션
=== 기본 실행
----
pg_dumpall[ connection-option...] [ option...]
----

=== connection 옵션
- `-d dbname` or `--dbname=dbname` +
데이터베이스의 이름을 지정합니다.
--dbname 옵션은 다른 클라이언트 응용 프로그램과의 일관성을 위해 호출되지만 pg_dumpall 은 많은 데이터베이스에 연결해야 하므로 연결 문자열의 데이터베이스 이름은 무시됩니다.

- `-h host` or `--host=host` +
호스트를 지정합니다. 값이 슬래시로 시작하면 Unix 도메인 소켓의 디렉토리로 사용합니다. Default 값은 PGHOST 환경변수에서 가져오며, 환경변수가 없다면 Unix 도메인 소켓 연결을 시도합니다.

- `-p port` or `--port=port` +
포트번호를 지정합니다.

- `-U username` or `--username=username` +
연결살 User name 입니다.

- `-w` or `--no-password` +
데이터베이스를 연결하기 전에 password 없이 명령어를 실행합니다. 해당 명령이 실행될 때 암호가 필요없다면(.pgpass) 바로 실행됩니다.

- `-W` or `--password` +
데이터베이스를 연결하기 전에 password를 물어봅니다.

- `--role=rolename` +
dump를 수행할 User의 Role을 설정합니다. pg_dump가 데이터베이스에 연결한 후에 명령을 실행하도록 설정됩니다. 만약 `-U` 로 설정된 User에 pg_dump를 실행할 권한이 없을 때 유용합니다.

== 3. pg_dumpall 백업 및 버전 업그레이드

=== 전체 데이터베이스 클러스터 백업 
----
pg_dumpall > db.out
----

=== 백업한 파일을 PostgreSQL 에서 로드
----
psql -f db.out postgres
----

=== 마이너 버전 업그레이드 

*1. 환경 세팅*
----
As-is Server : PostgreSQL 11.14v ( 데이터가 존재하는 서버 )
To-be Server : PostgreSQL 11.15v ( 업그레이드 할 환경으로 initdb로 데이터 클러스터 생성된 상태 )
----

*2. To-be Server 의 접속 연결 설정*
----
pg_hba.conf / postgresql.conf
As-is Server와 동일한 설정이 필요하다면 파일 백업 및 적용
----

*3. pg_dumpall As-is Server 에서 수행*
----
pg_dumpall -c | psql -p [To-be Server Port] -h [To-be Server IP]
----
