= btree_gin
:toc: 
:toc-title: 목차
:sectlinks:
:sectnums:

== btree_gin 설명
btree_gin은 데이터유형 int2, int4, int8, float4, float8, timestamp with time zone, timestamp without time zone, time with time zone, time without time zone, date, interval, oid, money, "char", varchar, text, bytea, bit, varbit, macaddr, macaddr8, inet, cidr, uuid, name, bool, bpchar 그리고 모든 enum 유형에 대해 b-tree에 해당되는 동작을 구현하는 샘플 GIN 연산자 클래스를 제공합니다.

일반적으로 이러한 연산자 클래스는 동등한 표준 b-tree 인덱스 방법을 능가하지 않으며, 표준 b-tree 코드의 한가지 주요 기능인 고유성을 적용하는 기능이 부족합니다. 그러나 GIN 연산자 클래스를 개발하는데 유용합니다. 그리고 GIN 인덱싱 가능 컬럼과 btree 인덱싱 가능 컬럼을 모두 테스트하는 쿼리의 경우 이 연산자 클래스 중 하나를 사용하는 다중 컬럼 GIN 인덱스를 만드는것이 두개의 별도 인덱스를 만드는 것보다 효율적입니다.

== btree_gin 예시
다음은 인덱스 생성시 GIN 을 적용하는 예시입니다.
[source, sql]
----
--bool 데이터타입 가진 테이블 생성
CREATE TABLE test_bool (i boolean);

--실행계획 확인
EXPLAIN (COSTS OFF) SELECT * FROM test_bool WHERE i<true ORDER BY i;
         QUERY PLAN          
-----------------------------
 Sort
   Sort Key: i
   ->  Seq Scan on test_bool
         Filter: (i < true)
(4 rows)

-- 인덱스 생성시 GIN 연산자 사용
CREATE INDEX idx_bool ON test_bool USING gin (i);

-- 실행계획 확인
EXPLAIN (COSTS OFF) SELECT * FROM test_bool WHERE i<true ORDER BY i;
                QUERY PLAN                 
-------------------------------------------
 Sort
   Sort Key: i
   ->  Bitmap Heap Scan on test_bool
         Recheck Cond: (i < true)
         ->  Bitmap Index Scan on idx_bool
               Index Cond: (i < true)
(6 rows)
----
