= file_fdw
:toc: 
:toc-title: 목차
:sectlinks:
:sectnums:

== file_fdw 설명
file_fdw 모듈은 서버의 파일 시스템에 있는 데이터 파일에 액세스하거나, 서버에서 프로그램을 실행하고 출력을 읽는 데 사용할 수 있는 외부 데이터 wrapper를 제공합니다. 데이터 파일 또는 프로그램 출력은 copy from 절에서 읽을 수 있는 형식이어야 합니다.(데이터 파일에 대한 액세스는 현재 읽기 전용)

이 wrapper를 사용하여 생성된 foreign 테이블에는 다음 옵션을 적용할 수 있습니다.

* filename - 읽을 파일을 지정합니다. 상대 경로는 데이터 디렉토리에 상대적입니다. 

* program - 실행할 명령을 지정합니다. 이 명령의 표준 출력은 copy from program이 사용된 것처럼 읽힙니다. filename or program 둘 중 하나만 지정 가능합니다.

* format - copy의 format 옵션과 동일한 데이터 형식을 지정합니다.

* header - copy의 header 옵션과 마찬가지로 데이터에 헤더가 있는지 여부를 지정합니다.

* delimiter - copy의 delimiter 옵션과 동일한 데이터 구분 문자를 지정합니다.

* quote - copy의 quote 옵션과 동일한 데이터 인용 문자를 지정합니다.

* escape - copy의 escape 옵션과 동일하게 데이터 이스케이프 문자를 지정합니다.

* null - copy의 null 옵션과 동일한 데이터 null 문자열을 지정합니다.

* encoding - copy의 enconding 옵션과 동일하게 데이터 인코딩을 지정합니다.


이 wrapper를 사용하여 생성된 foreign 테이블의 column에는 다음 옵션을 적용할 수 있습니다.

* force_not_null - boolean 옵션입니다. true면 column 값이 null 문자열과 일치하지 않아야함을 지정합니다(테이블 수준 null 옵션). 이는 copy의 force_not_null 옵션에 column을 나열하는 것과 동일한 효과를 가집니다.

* force_null - boolean 옵션입니다. true인 경우 null 문자열과 일치하는 column의 null 값이 따옴표로 묶인 경우에도 반환되도록 지정합니다. 이 옵션이 없으면 null 문자열과 일치하는 인용 부호가 없는 값믄 NULL로 반환됩니다. 이는 copy의 force_null 옵션에 열을 나열하는 것과 동일한 효과를 가집니다.

file_fdw의 명백한 용도 중 하나는 postgresql 활동 로그를 쿼리용 테이블로 사용할 수 있도록 하는 것입니다.

== file_fdw 예시
pglog를 csv로 로깅하여 쿼리용 테이블로 만들기 위해 file_fdw를 활용하는 예제입니다.
[source, sql]
----
--foreign 서버를 file_fdw wrapper로 생성합니다
CREATE SERVER pglog FOREIGN DATA WRAPPER file_fdw;

--foreign 테이블 생성합니다. filename의 경로를 지정하고 반드시 pglog.csv 파일이 있어야 합니다. 
CREATE FOREIGN TABLE pglog (
  log_time timestamp(3) with time zone,
  user_name text,
  database_name text,
  process_id integer,
  connection_from text,
  session_id text,
  session_line_num bigint,
  command_tag text,
  session_start_time timestamp with time zone,
  virtual_transaction_id text,
  transaction_id bigint,
  error_severity text,
  sql_state_code text,
  message text,
  detail text,
  hint text,
  internal_query text,
  internal_query_pos integer,
  context text,
  query text,
  query_pos integer,
  location text,
  application_name text,
  backend_type text,
  leader_pid integer,
  query_id bigint
) SERVER pglog
OPTIONS ( filename 'log 경로입력/pglog.csv', format 'csv' );

--로그를 직접 쿼리할 수 있음을 확인합니다.
select * from pglog;

 log_time | user_name | database_name | process_id | connection_from | session_id | session_line_num | command_tag |
 session_start_time | virtual_transaction_id | transaction_id | error_severity | sql_state_code | message | detail |
 hint | internal_query | internal_query_pos | context | query | query_pos | location | application_name | backend_ty
pe | leader_pid | query_id 
----------+-----------+---------------+------------+-----------------+------------+------------------+-------------+
--------------------+------------------------+----------------+----------------+----------------+---------+--------+
------+----------------+--------------------+---------+-------+-----------+----------+------------------+-----------
---+------------+----------
(0 rows)
----
