= fuzzystrmatch
:toc: 
:toc-title: 목차
:sectlinks:
:sectnums:

== fuzzystrmatch 설명
fuzzystrmatch 모듈은 문자열 간의 유사성과 거리를 결정하는 여러 기능을 제공합니다.

* soundex

소리가 비슷한 이름을 동일한 코드로 변환하여 일치시키는 방법입니다. 영어가 아닌 이름에는 유용하지 않습니다.
soundex 코드 작업을 위해 두가지 기능을 제공합니다.

soundex(text) returns text - 문자열을 soundex 코드로 변환 +
difference(text, text) returns int - 두 문자열을 soundex 코드로 변환 한 다음 일치하는 코드 위치 수를 보고. 결과는 0 ~ 4까지이며 0은 불일치, 4는 정확히 일치입니다.


* levenshtien

두 문자열 사이의 levenshtien 거리를 계산합니다. Levenshtein 거리는 한 string s1 을 s2 로 변환하는 최소 횟수를 두 string 간의 거리로 정의합니다. 예를 들어 s1 = '꿈을꾸는아이' 에서 s2 = '아이오아이' 로 바뀌기 위해서는 (꿈을꾸 -> 아이오) 로 바뀌고, 네번째 글자 '는' 이 제거되면 됩니다.

제공되는 기능은 다음과 같습니다.

levenshtein(text source, text target, int ins_cost, int del_cost, int sub_cost) returns int - source, target 모두 최대 255자의 null이 아닌 문자열일 수 있고, cost는 각각 문자 삽입, 삭제 또는 대체에 대한 비용입니다. +
levenshtein(text source, text target) returns int - 매개변수 생략된 버전입니다. +
levenshtein_less_equal(text source, text target, int ins_cost, int del_cost, int sub_cost, int max_d) returns int - 작은 거리만 관심이 있을 때 사용하기 위한 버전+
levenshtein_less_equal(text source, text target, int max_d) returns int

* metaphone

soundex와 마찬가지로 입력 문자열에 대한 대표 코드를 구성합니다. 제공되는 기능은 다음과 같습니다.

metaphone(text source, int max_output_length) returns text - 소스는 최대 255자의 null이 아닌 문자열이어야합니다. max_output_length는 최대길이로, 이보다 길면 잘립니다.

* double metaphone(dmetaphone)

주어진 입력 문자열에 대해 "기본" 문자열, "대체" 문자열의 두가지 "음향 유사" 문자열을 계산합니다. 영어가 아닌 이름의 경우 발음에 따라 약간 다를 수 있습니다. 제공되는 기능은 다음과 같습니다.

dmetaphone(text source) returns text +
dmetaphone_alt(text source) returns text

입력문자열 길이에는 제한이 없습니다.

== fuzzystrmatch 예시
soundex의 예시입니다.
[source,sql]
----
SELECT soundex('hello world!');
 soundex 
---------
 H464
(1 row)

SELECT soundex('Anne'), soundex('Ann'), difference('Anne', 'Ann');
 soundex | soundex | difference 
---------+---------+------------
 A500    | A500    |          4
(1 row)

SELECT soundex('Anne'), soundex('Andrew'), difference('Anne', 'Andrew');
 soundex | soundex | difference 
---------+---------+------------
 A500    | A536    |          2
(1 row)

SELECT soundex('Anne'), soundex('Margaret'), difference('Anne', 'Margaret');
 soundex | soundex | difference 
---------+---------+------------
 A500    | M626    |          0
(1 row)
----

levenshtein의 예시입니다.
[source,sql]
----
SELECT levenshtein('GUMBO', 'GAMBOL'); 
 levenshtein 
------------- 
           2 
(1 행) 

SELECT levenshtein('GUMBO', 'GAMBOL', 2, 1, 1); 
 levenshtein 
------------- 
           3 
(1 행) 

SELECT levenshtein_less_equal('extensive', 'exhaustive', 2); 
 levenshtein_less_equal 
------------------------ 
                      3 
(1행) 

SELECT levenshtein_less_equal('extensive', 'exhaustive', 4); 
 levenshtein_less_equal 
------------------------ 
                      4 
(1 행)


----

metaphon의 예시입니다.
[source,sql]
----
SELECT metaphone('GUMBO', 4);
 metaphone
-----------
 KM
(1 row)
----


dmataphone의 예시입니다.
[source,sql]
----
SELECT dmetaphone('gumbo');
 dmetaphone
------------
 KMP
(1 row)

SELECT dmetaphone_alt('gumbo');
 dmetaphone_alt 
----------------
 KMP
(1 row)
----