= hstore
:toc: 
:toc-title: 목차
:sectlinks:
:sectnums:

== hstore 설명
hstore은 단일 PostgreSQL 값 내에 key - value 세트를 저장하기 위한 데이터 유형을 구현합니다. key 와 value는 단순한 text 문자열입니다.

* hstore external representation

입력 및 출력에 사용되는 hstore의 텍스트 표현에는 쉼표로 구분된 0개 이상의 key => value 쌍이 포함됩니다. 예시로,

 k => v +
 foo => bar, baz => whatever +
 "1-a" => "anything at all" +

=> 기호 주의의 공백은 무시되며 키 또 는 값에 큰따옴표나 백슬래시를 포함하려면 백슬래시로 이스케이프 해야합니다.

 hstore의 각 키는 고유합니다. 중복 키를 사용하여 선언하면 하나만 저장되며, 어떤 키가 유지될 지 보장할 수 없습니다. 값은 NULL이 선언 될 수 있습니다. NULL을 일반 문자열로 처리하려면 "NULL" 과 같이 사용합니다.
[source, sql]
----
SELECT 'a=>1,a=>2'::hstore;
  hstore
----------
 "a"=>"1"
----

* hstore operators

*hstore -> text → text* - 주어진 키와 관련된 값을 반환하거나 존재하지 않는 경우 NULL을 반환합니다. +
예) 'a=>x, b=>y'::hstore -> 'a' → x

*hstore -> text[] → text[]* - 주어진 키와 관련된 값을 반환하거나 존재하지 않는 경우 NULL을 반환합니다. +
예) 'a=>x, b=>y, c=>z'::hstore -> ARRAY['c','a'] → {"z","x"}

*hstore || hstore → hstore* - 두개의 hstores를 연결합니다. +
예) 'a=>b, c=>d'::hstore || 'c=>x, d=>q'::hstore → "a"=>"b", "c"=>"x", "d"=>"q"

*hstore ? text → boolean* - hstore가 키를 포함하는지 확인합니다. +
예) 'a=>1'::hstore ? 'a' → t

*hstore ?& text[] → boolean* - hstore가 특정한 모든 키를 포함하고 있는지 확인합니다 +
예) 'a=>1,b=>2'::hstore ?& ARRAY['a','b'] → t

*hstore ?| text[] → boolean* - hstore가 특정한 키를 포함하고 있는지 확인합니다. +
예) 'a=>1,b=>2'::hstore ?| ARRAY['b','c'] → t

*hstore @> hstore → boolean* - 왼쪽 피연산자에 오른쪽이 포함되는지 확인합니다. +
예) 'a=>b, b=>1, c=>NULL'::hstore @> 'b=>1' → t

*hstore <@ hstore → boolean* - 왼쪽 피연산자가 오른쪽에 포함되는지 확인합니다. +
예) 'a=>c'::hstore <@ 'a=>b, b=>1, c=>NULL' → f

*hstore - text → hstore* - 왼쪽 피연산자에서 키를 삭제합니다. +
예) 'a=>1, b=>2, c=>3'::hstore - 'b'::text → "a"=>"1", "c"=>"3"

*hstore - text[] → hstore* - 키를 삭제합니다. +
예) 'a=>1, b=>2, c=>3'::hstore - ARRAY['a','b'] → "c"=>"3"

*hstore - hstore → hstore* - 오른쪽 피연산자의 쌍과 일치하는 쌍을 왼쪽 피연산자에서 삭제합니다. +
예) 'a=>1, b=>2, c=>3'::hstore - 'a=>4, b=>2'::hstore → "a"=>"1", "c"=>"3"

*anyelement #= hstore → anyelement* - 왼쪽 피연산자(복합유형)의 필드를 hstore의 일치하는 값으로 바꿉니다. +
예) ROW(1,3) #= 'f1=>11'::hstore → (11,3)

*%% hstore → text[]* - hstore을 키와 값의 배열로 변환합니다. +
예) %% 'a=>foo, b=>bar'::hstore → {a,foo,b,bar}

*%# hstore → text[]* - hstore을 2차원 키와 값의 배열로 변환합니다. +
예) %# 'a=>foo, b=>bar'::hstore → {{a,foo},{b,bar}}

* hstore functions

*hstore ( record ) → hstore* - 레코드 또는 행에서 hstore을 구성합니다. +
예) hstore(ROW(1,2)) → "f1"=>"1", "f2"=>"2"

*hstore ( text[] ) → hstore* - 키/값 배열 또는 2차원 배열에서 hsotre을 구성합니다. +
예) hstore(ARRAY['a','1','b','2']) → "a"=>"1", "b"=>"2" +
hstore(ARRAY[['c','3'],['d','4']]) → "c"=>"3", "d"=>"4"

*hstore ( text[], text[] ) → hstore* - 별도의 키 및 값 배열에서 hstore을 구성합니다. +
예) hstore(ARRAY['a','b'], ARRAY['1','2']) → "a"=>"1", "b"=>"2"

*hstore ( text, text ) → hstore* - hstore 단일 항목을 만듭니다. +
예) hstore('a', 'b') → "a"=>"b"

*akeys ( hstore ) → text[]* - hstore의 키를 배열로 추출합니다 +
예) akeys('a=>1,b=>2') → {a,b}

*skeys ( hstore ) → setof text* - hstore의 키을 세트로 추출합니다 +
예) skeys('a=>1,b=>2') → +
a +
b

*avals ( hstore ) → text[]* - hstore의 값를 배열로 추출합니다. +
예) avals('a=>1,b=>2') → {1,2}

*svals ( hstore ) → setof text* - hstore의 값을 집합으로 추출합니다. +
예) svals('a=>1,b=>2') → +
1 +
2

*hstore_to_array ( hstore ) → text[]* - hstore의 키와 값을 키와 값의 배열로 바꿔 추출합니다. +
예) hstore_to_array('a=>1,b=>2') → {a,1,b,2}

*hstore_to_matrix ( hstore ) → text[]* - hstore의 키와 값을 2차원 배열로 추출합니다. +
예) hstore_to_matrix('a=>1,b=>2') → {{a,1},{b,2}}

*hstore_to_json ( hstore ) → json* - hstore를 json 값으로 변환하고, null이 아닌 모든 값을 json 문자열로 변환합니다. 이 함수는 hstore 값이 json으로 캐스트 될 때 암시적으로 사용됩니다. +
예) hstore_to_json('"a key"=>1, b=>t, c=>null, d=>12345, e=>012345, f=>1.234, g=>2.345e+4') → {"a key": "1", "b": "t", "c": null, "d": "12345", "e": "012345", "f": "1.234", "g": "2.345e+4"}

*hstore_to_jsonb ( hstore ) → jsonb* - hstore를 jsonb 값으로 변환하고, null이 아닌 모든 값을 json 문자열로 변환합니다. 이 함수는 hstore 값이 jsonb로 캐스트 될 때 암시적으로 사용됩니다. +
예) hstore_to_jsonb('"a key"=>1, b=>t, c=>null, d=>12345, e=>012345, f=>1.234, g=>2.345e+4') → {"a key": "1", "b": "t", "c": null, "d": "12345", "e": "012345", "f": "1.234", "g": "2.345e+4"}

*hstore_to_json_loose ( hstore ) → json* - hstore를 json 값으로 변환하지만 숫자 값과 부울 값을 구별하려고 시도하므로 json에서 인용되지 않습니다. +
예) hstore_to_json_loose('"a key"=>1, b=>t, c=>null, d=>12345, e=>012345, f=>1.234, g=>2.345e+4') → {"a key": 1, "b": true, "c": null, "d": 12345, "e": "012345", "f": 1.234, "g": 2.345e+4}

*hstore_to_jsonb_loose ( hstore ) → jsonb* - hstore를 jsonb 값으로 변환하지만 숫자 값과 부울 값을 구별하려고 시도하므로 json에서 인용되지 않습니다. +
예) hstore_to_jsonb_loose('"a key"=>1, b=>t, c=>null, d=>12345, e=>012345, f=>1.234, g=>2.345e+4') → {"a key": 1, "b": true, "c": null, "d": 12345, "e": "012345", "f": 1.234, "g": 2.345e+4}

*slice ( hstore, text[] ) → hstore* - 지정된 키만 포함하는 hstore의 하위 집합을 추출합니다. +
예) slice('a=>1,b=>2,c=>3'::hstore, ARRAY['b','c','x']) → "b"=>"2", "c"=>"3"

*each ( hstore ) → setof record ( key text, value text )* - hstore의 키와 값을 레코드 세트로 추출합니다. +
예) 
[source,sql]
----
select * from each('a=>1,b=>2') →
 key | value
-----+-------
 a   | 1
 b   | 2
----

*exist ( hstore, text ) → boolean* - hstore가 key를 가지고 있는지 확인합니다. +
예) exist('a=>1', 'a') → t

*defined ( hstore, text ) → boolean* - hstore가 NULL이 아닌 값을 가지고 있는지 확인합니다. +
예) defined('a=>NULL', 'a') → f

*delete ( hstore, text ) → hstore* - 일치하는 키가 있는 쌍을 삭제합니다. +
예) delete('a=>1,b=>2', 'b') → "a"=>"1"

*delete ( hstore, text[] ) → hstore* - 일치하는 키가 있는 쌍을 삭제합니다 +
예) delete('a=>1,b=>2,c=>3', ARRAY['a','b']) → "c"=>"3"

*delete ( hstore, hstore ) → hstore* - 두번째 인수와 일치하는 쌍을 삭제합니다. +
예) delete('a=>1,b=>2', 'a=>4,b=>2'::hstore) → "a"=>"1"

*populate_record ( anyelement, hstore ) → anyelement* - 왼쪽 피연산자(복합유형)의 필드를 hstore에 일치하는 값으로 바꿉니다. +
예) populate_record(ROW(1,2), 'f1=>42'::hstore) → (42,2)

이러한 연산자 및 함수 외에도 hstore 유형의 값을 첨자로 작성할 수 있어 연관 배열처럼 동작할 수 있습니다. text 유형의 단일 첨자만 지정할 수 있습니다.
예)
[source,sql]
----
CREATE TABLE mytable (h hstore);
INSERT INTO mytable VALUES ('a=>b, c=>d');
SELECT h['a'] FROM mytable;
 h
---
 b
(1 row)

UPDATE mytable SET h['c'] = 'new';
SELECT h FROM mytable;
          h
----------------------
 "a"=>"b", "c"=>"new"
(1 row)
----

* index

hstore은 @>, ?, ?&, ?| 연산자에 대해 GiST 및 GIN 인덱스를 지원합니다. +
예) CREATE INDEX hidx ON testhstore USING GIST (h); +
CREATE INDEX hidx ON testhstore USING GIN (h); +
gist_hstore_ops를 이용해 키/값 세트를 비트맵 signature로 근사 +
CREATE INDEX hidx ON testhstore USING GIST (h gist_hstore_ops(siglen=32));

hstore은 = 연산자에 대한 btree 또는 hash 인덱스도 지원합니다. 이를 통해 hstore 컬럼을 unique로 선언하거나 group by, order by 도는 distinct 식에서 사용할 수 있습니다. +
예) CREATE INDEX hidx ON testhstore USING BTREE (h); +
CREATE INDEX hidx ON testhstore USING HASH (h);

* statistics

hstore 유형은 고유한 자유도 때문에 다양한 키를 포함할 수 있습니다. 유효한 키를 확인하는 것은 애플리케이션의 작업입니다. 키를 확인하고 통계를 얻기 위한 몇가지 예입니다. +
예)
[source,sql]
----
SELECT * FROM each('aaa=>bq, b=>NULL, ""=>1');

CREATE TABLE stat AS SELECT (each(h)).key, (each(h)).value FROM testhstore;

--온라인 통계
SELECT key, count(*) FROM
  (SELECT (each(h)).key FROM testhstore) AS stat
  GROUP BY key
  ORDER BY count DESC, key;
    key    | count
-----------+-------
 line      |   883
 query     |   207
 pos       |   203
 node      |   202
 space     |   197
 status    |   195
 public    |   194
 title     |   190
 org       |   189
...................
----

* Compatibility

hstore는 PostgreSQL 9.0 부터 이전 버전과 다른 내부 표현을 사용합니다. 이는 덤프에 사용되는 텍스트 표현이 변경되지 않기 때문에 덤프/복원, 업그레이드에 장애가 되지 않습니다. 바이너리 업그레이드의 경우 새 코드가 이전 형식 데이터를 인식하도록 하여 상위 호환성이 유지됩니다. 이는 새 코드에 의해 아직 수정되지 않은 데이터를 처리할 때 약간의 성능 저하를 수반합니다. 다음과 같이 update 명령문을 수행하여 테이블 열의 모든 값을 강제로 업그레이드 할 수 있습니다. +
예)
[source,sql]
----
UPDATE tablename SET hstorecol = hstorecol || '';

ALTER TABLE tablename ALTER hstorecol TYPE hstore USING hstorecol || '';
----

* Transforms

PL/Perl 및 PL/Python 언어의 hstore 유형에 대한 변환을 구현하는 추가 extension을 사용할 수 있습니다. PL/Perl extension은 hstore_plperl, hstore_plperlu라고 하며 이를 설치하고 함수를 생성할 때 지정하면 hstore 값이 Perl 해시에 매핑됩니다. PL/Python extension은 hstore_plpythonu, hstore_plpython2u, hstore_plpython3u라고 하며, hstore 값이 python 사전에 매핑됩니다.

== hstore 예시
다음은 hstore에서 제공하는 기능을 통해 key - value를 다루는 예시입니다.
[source, sql]
----
select 'a=>b'::hstore;
  hstore  
----------
 "a"=>"b"
(1 row)

select '"a"=> "b"'::hstore;
  hstore  
----------
 "a"=>"b"
(1 row)

select ('aa=>"NULL", c=>d , b=>16'::hstore->'aa') is null;
 ?column? 
----------
 f
(1 row)

select exist('a=>NULL, b=>qq', 'a');
 exist 
-------
 t
(1 row)

select defined('a=>NULL, b=>qq', 'a');
 defined 
---------
 f
(1 row)

select delete('a=>1 , b=>2, c=>3'::hstore, 'a');
       delete       
--------------------
 "b"=>"2", "c"=>"3"
(1 row)

select pg_column_size(hstore(v))
         = pg_column_size('a=>1, b=>"foo", c=>"1.2", d=>"3", e=>"0"'::hstore)
  from testhstore1 v;
 ?column? 
----------
 t
(1 row)

select populate_record(v, hstore('c', '3.45')) from testhstore1 v;
 populate_record  
------------------
 (1,foo,3.45,3,0)
(1 row)

select hstore_to_array('aa=>1, cq=>l, b=>g, fg=>NULL'::hstore);
     hstore_to_array     
-------------------------
 {b,g,aa,1,cq,l,fg,NULL}
(1 row)

CREATE TABLE test (col1 integer, col2 text, col3 text);

SELECT * FROM populate_record(null::test,
                              '"col1"=>"456", "col2"=>"zzz"');
 col1 | col2 | col3 
------+------+------
  456 | zzz  | 
(1 row)
----