= intarray
:toc: 
:toc-title: 목차
:sectlinks:
:sectnums:

== intarray 설명
null이 없는 정수 배열을 조작하는데 유용한 여러 함수와 연산자를 제공합니다. 일부 연산자를 사용하는 index 검색도 지원 됩니다. 제공된 배열에 null 요소가 포함되어 있으면 모든 작업에서 오류가 발생합니다. 2차원 이상의 배열을 허용하긴 하나, 데이터 저장순서에서 선형(1차원) 배열인 것처럼 처리됩니다.

* intarray에서 제공하는 함수는 아래와 같습니다.

icount ( integer[] ) returns integer - 배열의 요소 수를 반환합니다. +
예) icount('{1,2,3}'::integer[]) → 3

sort ( integer[], dir text ) returns integer[] - 배열을 오름차순 또는 내림차순으로 정렬합니다. dir은 asc , desc중 하나여야합니다. +
예) sort('{1,3,2}'::integer[], 'desc') → {3,2,1}

sort ( integer[] ) returns integer[] + 
sort_asc ( integer[] ) returns integer[] - 오름차순으로 정렬합니다. +
예) sort(array[11,77,44]) → {11,44,77}

sort_desc ( integer[] ) returns integer[] - 내림차순으로 정렬합니다. +
예) sort_desc(array[11,77,44]) → {77,44,11}

uniq ( integer[] ) returns integer[] - 인접한 중복을 제거합니다. 모든 중복을 제거하기 위해 sort와 함께 사용됩니다. +
예) uniq('{1,2,2,3,1,1}'::integer[]) → {1,2,3,1} +
uniq(sort('{1,2,3,2,1}'::integer[])) → {1,2,3}

idx ( integer[], item integer ) returns integer - item과 일치하는 첫 번째 배열 요소의 인덱스를 반환 하거나 일치하지 않으면 0을 반환합니다. +
예) idx(array[11,22,33,22,11], 22) → 2

subarray ( integer[], start integer, len integer ) returns integer[] - start 위치에서 시작하는 배열 부분을 len 요소와 함께 추출합니다. +
예) subarray('{1,2,3,2,1}'::integer[], 2, 3) → {2,3,2}

subarray ( integer[], start integer ) returns integer[] - start 위치에서 시작하는 배열 부분을 추출합니다. +
예) subarray('{1,2,3,2,1}'::integer[], 2) → {2,3,2,1}

intset ( integer ) returns integer[] - 단일 요소 배열을 만듭니다. +
예) intset(42) → {42}


* intarray에서 제공하는 연산자는 아래와 같습니다.

integer[] && integer[] → boolean - 배열이 겹치는지 확인합니다. (공통 요소가 최소 하나 이상 있는지)?

integer[] @> integer[] → boolean - 왼쪽 배열에 오른쪽 배열이 포함되어 있는지 확인합니다.

integer[] <@ integer[] → boolean - 왼쪽 배열이 오른쪽 배열에 포함되어 있는지 확인합니다.

#integer[] → integer - 배열의 요소 수를 반환합니다.

integer[] # integer → integer - 오른쪽 인수와 일치하는 첫 번째 배열 요소의 인덱스를 반환하거나, 일치하지 않으면 0을 반환합니다.(idx 함수와 동일합니다.)

integer[] + integer → integer[] - 배열의 끝에 요소를 추가합니다.

integer[] + integer[] → integer[] - 배열을 연결합니다.

integer[] - integer → integer[] - 배열에서 올바른 인수와 일치하는 항목을 제거합니다.

integer[] - integer[] → integer[] - 왼쪽 배열에서 오른쪽 배열의 요소를 제거합니다.

integer[] | integer → integer[] - 인수의 합집합을 계산합니다.

integer[] | integer[] → integer[] - 인수의 합집합을 계산합니다.

integer[] & integer[] → integer[] - 인수의 교집합을 계산합니다.

integer[] @@ query_int → boolean - 배열이 쿼리를 만족하는지 확인합니다.(쿼리는 특수 데이터 형식의 값으로 표현됨)

query_int ~~ integer[] → boolean - 배열이 쿼리를 만족하는지 확인합니다.(commutator of @@)

&&, @>및 @@연산자에 대한 인덱스 지원 과 일반 배열 동등성을 제공합니다. 그리고 GIST 인덱스 연산자 클래스가 제공됩니다.


== intarray 예시
intarray에서 제공하는 함수와 연산자를 활용하는 예시입니다.

[source, sql]
----
SELECT intset(1234);
 intset 
--------
 {1234}
(1 row)

SELECT icount('{1234234,234234}');
 icount 
--------
      2
(1 row)

SELECT sort('{1234234,-30,234234}');
         sort         
----------------------
 {-30,234234,1234234}
(1 row)

SELECT sort('{1234234,-30,234234}','asc');
         sort         
----------------------
 {-30,234234,1234234}
(1 row)

SELECT sort('{1234234,-30,234234}','desc');
         sort         
----------------------
 {1234234,234234,-30}
(1 row)

SELECT sort_asc('{1234234,-30,234234}');
       sort_asc       
----------------------
 {-30,234234,1234234}
(1 row)

SELECT sort_desc('{1234234,-30,234234}');
      sort_desc       
----------------------
 {1234234,234234,-30}
(1 row)

SELECT uniq('{1234234,-30,-30,234234,-30}');
           uniq           
--------------------------
 {1234234,-30,234234,-30}
(1 row)

SELECT uniq(sort_asc('{1234234,-30,-30,234234,-30}'));
         uniq         
----------------------
 {-30,234234,1234234}
(1 row)

SELECT idx('{1234234,-30,-30,234234,-30}',-30);
 idx 
-----
   2
(1 row)

SELECT subarray('{1234234,-30,-30,234234,-30}',2,3);
     subarray     
------------------
 {-30,-30,234234}
(1 row)

SELECT subarray('{1234234,-30,-30,234234,-30}',-1,1);
 subarray 
----------
 {-30}
(1 row)

SELECT subarray('{1234234,-30,-30,234234,-30}',0,-1);
         subarray         
--------------------------
 {1234234,-30,-30,234234}
(1 row)

SELECT #'{1234234,234234}'::int[];
 ?column? 
----------
        2
(1 row)

SELECT '{123,623,445}'::int[] + 1245;
      ?column?      
--------------------
 {123,623,445,1245}
(1 row)

SELECT '{123,623,445}'::int[] + 445;
     ?column?      
-------------------
 {123,623,445,445}
(1 row)

SELECT '{123,623,445}'::int[] + '{1245,87,445}';
         ?column?          
---------------------------
 {123,623,445,1245,87,445}
(1 row)

SELECT '{123,623,445}'::int[] - 623;
 ?column?  
-----------
 {123,445}
(1 row)

SELECT '{123,623,445}'::int[] - '{1623,623}';
 ?column?  
-----------
 {123,445}
(1 row)

SELECT '{123,623,445}'::int[] | 623;
   ?column?    
---------------
 {123,445,623}
(1 row)

SELECT '{123,623,445}'::int[] | 1623;
      ?column?      
--------------------
 {123,445,623,1623}
(1 row)

SELECT '{123,623,445}'::int[] | '{1623,623}';
      ?column?      
--------------------
 {123,445,623,1623}
(1 row)

SELECT '{123,623,445}'::int[] & '{1623,623}';
 ?column? 
----------
 {623}
(1 row)

SELECT '{-1,3,1}'::int[] & '{1,2}';
 ?column? 
----------
 {1}
(1 row)

SELECT '{1}'::int[] & '{2}'::int[];
 ?column? 
----------
 {}
(1 row)

SELECT array_dims('{1}'::int[] & '{2}'::int[]);
 array_dims 
------------
 
(1 row)

SELECT ('{1}'::int[] & '{2}'::int[]) = '{}'::int[];
 ?column? 
----------
 t
(1 row)

SELECT ('{}'::int[] & '{}'::int[]) = '{}'::int[];
 ?column? 
----------
 t
(1 row)

--test query_int
SELECT '1'::query_int;
 query_int 
-----------
 1
(1 row)

SELECT ' 1'::query_int;
 query_int 
-----------
 1
(1 row)

SELECT '1 '::query_int;
 query_int 
-----------
 1
(1 row)

SELECT ' 1 '::query_int;
 query_int 
-----------
 1
(1 row)

SELECT ' ! 1 '::query_int;
 query_int 
-----------
 !1
(1 row)

SELECT '!1'::query_int;
 query_int 
-----------
 !1
(1 row)

SELECT '1|2'::query_int;
 query_int 
-----------
 1 | 2
(1 row)

SELECT '1|!2'::query_int;
 query_int 
-----------
 1 | !2
(1 row)

SELECT '!1|2'::query_int;
 query_int 
-----------
 !1 | 2
(1 row)

SELECT '!1|!2'::query_int;
 query_int 
-----------
 !1 | !2
(1 row)

SELECT '!(!1|!2)'::query_int;
  query_int   
--------------
 !( !1 | !2 )
(1 row)

SELECT '!(!1|2)'::query_int;
  query_int  
-------------
 !( !1 | 2 )
(1 row)

SELECT '!(1|!2)'::query_int;
  query_int  
-------------
 !( 1 | !2 )
(1 row)

SELECT '!(1|2)'::query_int;
 query_int  
------------
 !( 1 | 2 )
(1 row)

SELECT '1&2'::query_int;
 query_int 
-----------
 1 & 2
(1 row)

SELECT '!1&2'::query_int;
 query_int 
-----------
 !1 & 2
(1 row)

SELECT '1&!2'::query_int;
 query_int 
-----------
 1 & !2
(1 row)

SELECT '!1&!2'::query_int;
 query_int 
-----------
 !1 & !2
(1 row)

SELECT '(1&2)'::query_int;
 query_int 
-----------
 1 & 2
(1 row)

SELECT '1&(2)'::query_int;
 query_int 
-----------
 1 & 2
(1 row)

SELECT '!(1)&2'::query_int;
 query_int 
-----------
 !1 & 2
(1 row)

SELECT '!(1&2)'::query_int;
 query_int  
------------
 !( 1 & 2 )
(1 row)

SELECT '1|2&3'::query_int;
 query_int 
-----------
 1 | 2 & 3
(1 row)

SELECT '1|(2&3)'::query_int;
 query_int 
-----------
 1 | 2 & 3
(1 row)

SELECT '(1|2)&3'::query_int;
   query_int   
---------------
 ( 1 | 2 ) & 3
(1 row)

SELECT '1|2&!3'::query_int;
 query_int  
------------
 1 | 2 & !3
(1 row)

SELECT '1|!2&3'::query_int;
 query_int  
------------
 1 | !2 & 3
(1 row)

SELECT '!1|2&3'::query_int;
 query_int  
------------
 !1 | 2 & 3
(1 row)

SELECT '!1|(2&3)'::query_int;
 query_int  
------------
 !1 | 2 & 3
(1 row)

SELECT '!(1|2)&3'::query_int;
   query_int    
----------------
 !( 1 | 2 ) & 3
(1 row)

SELECT '(!1|2)&3'::query_int;
   query_int    
----------------
 ( !1 | 2 ) & 3
(1 row)

SELECT '1|(2|(4|(5|6)))'::query_int;
           query_int           
-------------------------------
 1 | ( 2 | ( 4 | ( 5 | 6 ) ) )
(1 row)

SELECT '1|2|4|5|6'::query_int;
           query_int           
-------------------------------
 ( ( ( 1 | 2 ) | 4 ) | 5 ) | 6
(1 row)

SELECT '1&(2&(4&(5&6)))'::query_int;
     query_int     
-------------------
 1 & 2 & 4 & 5 & 6
(1 row)

SELECT '1&2&4&5&6'::query_int;
     query_int     
-------------------
 1 & 2 & 4 & 5 & 6
(1 row)

SELECT '1&(2&(4&(5|6)))'::query_int;
       query_int       
-----------------------
 1 & 2 & 4 & ( 5 | 6 )
(1 row)

SELECT '1&(2&(4&(5|!6)))'::query_int;
       query_int        
------------------------
 1 & 2 & 4 & ( 5 | !6 )
(1 row)
----