= ltree
:toc: 
:toc-title: 목차
:sectlinks:
:sectnums:

== ltree 설명
ltree는 계층적 트리와 같은 구조에서 저장된 데이터의 레이블을 나타내기 위한 데이터 유형 ltree를 구현합니다. 레이블 트리를 통해 검색할 수 있는 광범위한 기능이 제공됩니다.

* definitions

레이블은 일련의 영숫자 문자와 밑줄입니다(예: C locale에서는 문자 A-Za-z0-9_가 허용됨 ). 레이블은 256자 미만이어야 합니다. 레이블 경로는 점으로 구분된 0개 이상의 레이블 시퀀스입니다. 레이블 경로의 길이는 65535개 레이블을 초과할 수 없습니다.

다음과 같이 여러 ltree 데이터 유형을 제공합니다.

*ltree는 레이블 경로를 저장합니다.*

*lquery는 ltree 값을 일치시키기 위한 정규식과 같은 패턴을 나타냅니다.* +
간단한 단어는 경로 내의 해당 레이블과 일치합니다. 별 기호는 0개 이상의 레이블과 일치합니다. 이것들은 점으로 결합되어 전체 레이블 경로와 일치해야 하는 패턴을 형성할 수 있습니다. +

 foo         정확한 레이블 경로 foo와 일치
 *.foo.*     foo 레이블을 포함하는 모든 레이블 경로와 일치
 *.foo       마지막 레이블이 foo인 레이블 경로와 일치

별 기호와 간단한 단어를 수량화 하여 일치시킬 수 있는 레이블 수를 제한할 수 있습니다. +

 *{n}        정확히 n개의 레이블과 일치
 *{n,}       n개 이상의 레이블과 일치
 *{n,m}      n개 이상 m개 이하의 레이블과 일치
 *{,m}       최대 m개의 레이블과 일치 - *{0,m}과 동일
 foo{n,m}    foo가 n개 이상 m개 이하로 일치합니다.
 foo{,}      0을 포함하여 foo의 발생 횟수와 일치합니다.

명시적 수량자가 없는 경우 별표 기호의 기본값은 임의의 수의 레이블과 일치하는 반면, 별표가 아닌 항목의 기본값은 정확히 한 번 일치하는 것입니다.

정확히 일치하도록 하기 위해 별이 아닌 항목의 끝에 넣을 수 있는 몇가지 수정자가 있습니다. +

 @           대소문자를 구분하지 않고 일치합니다. 예를 들어 @는 A와 일치합니다.
 *           이 접두사가 있는 모든 레이블과 일치합니다. 예를 들어 foo*는 foobar와 일치합니다.
 %           밑줄로 구분된 첫 단어 일치

*ltxtquery는 일치하는 ltree 값에 대한 전체 텍스트 검색과 유사한 패턴을 나타냅니다.* +
ltxtquery 값에는 끝에 @, *, % 수정자가 있을 수 있는 단어가 포함됩니다. 수정자는 lquery에서와 같은 의미를 갖습니다. 단어는 &(AND), | (또는), ! (NOT) 및 괄호입니다. lquery와의 주요 차이점은 ltxtquery가 레이블 경로에서의 위치에 관계없이 단어와 일치한다는 것입니다.

* operators

ltree 유형에는 일반적인 비교 연산자 =, <>, <, >, <=, >=가 있습니다. 비교는 레이블 텍스트로 정렬된 노드의 자식과 함께 트리 순회 순서로 정렬됩니다. 그리고 아래 연산자도 추가로 지원합니다.

*ltree @> ltree → boolean* - 왼쪽 인수가 오른쪽(또는 동일한)의 조상인지 확인합니다.

*ltree <@ ltree → boolean* - 왼쪽 인수가 오른쪽(또는 동일한)의 자손인지 확인합니다.

*ltree ~ lquery → boolean* +
*lquery ~ ltree → boolean* - ltree가 lquery와 일치하는지 확인합니다.

*ltree ? lquery[] → boolean* +
*lquery[] ? ltree → boolean* - ltree가 배열의 lquery와 일치하는지 확인합니다.

*ltree @ ltxtquery → boolean* +
*ltxtquery @ ltree → boolean* - ltree가 ltxtquery와 일치하는지 확인합니다.

*ltree || ltree → ltree* - ltree 경로를 연결합니다.

*ltree || text → ltree* +
*text || ltree → ltree* - 텍스트를 ltree로 변환하고 연결합니다.

*ltree[] @> ltree → boolean* +
*ltree <@ ltree[] → boolean* - 배열에 ltree의 조상이 포함되어있는지 확인합니다.

*ltree[] <@ ltree → boolean* +
*ltree @> ltree[] → boolean* - 배열에 ltree의 자손이 포함되어있는지 확인합니다.

*ltree[] ~ lquery → boolean* +
*lquery ~ ltree[] → boolean* - 배열에 lquery와 일치하는 경로가 있는지 확인합니다.

*ltree[] ? lquery[] → boolean* +
*lquery[] ? ltree[] → boolean* - ltree 배열에 lquery와 일치하는 경로가 있는지 확인합니다.

*ltree[] @ ltxtquery → boolean* +
*ltxtquery @ ltree[] → boolean* - 배열에 ltxtquery와 일치하는 경로가 있는지 확인합니다.

*ltree[] ?@> ltree → ltree* - ltree의 조상인 첫 번째 배열 항목을 반환하거나 없는 경우 NULL을 반환합니다.

*ltree[] ?<@ ltree → ltree* - ltree의 자손인 첫 번째 배열 항목을 반환하거나 없는 경우 NULL을 반환합니다.

*ltree[] ?~ lquery → ltree* - lquery와 일치하는 첫 번째 배열 항목을 반환하거나 일치하지 않으면 NULL을 반환합니다.

*ltree[] ?@ ltxtquery → ltree* - ltxtquery와 일치하는 첫 번째 배열 항목을 반환하거나 일치하지 않으면 NULL을 반환합니다.


* functions

*subltree ( ltree, start integer, end integer ) → ltree* - 위치 시작에서 위치 끝-1 까지 ltree의 하위 경로를 반환합니다(0부터 계산). +
예) subltree('Top.Child1.Child2', 1, 2) → Child1

*subpath ( ltree, offset integer, len integer ) → ltree* - 오프셋 위치에서 시작하여 길이가 len인 ltree의 하위 경로를 반환합니다. 오프셋이 음수이면 하위 경로는 경로 끝에서 멀리 시작합니다. len이 음수이면 경로 끝에서 많은 레이블을 남겨 둡니다. +
예) subpath('Top.Child1.Child2', 0, 2) → Top.Child1

*subpath ( ltree, offset integer ) → ltree* - 오프셋 위치에서 시작하여 경로 끝까지 확장되는 ltree의 하위 경로를 반환합니다. 오프셋이 음수이면 하위 경로는 경로 끝에서 멀리 시작합니다. +
예) subpath('Top.Child1.Child2', 1) → Child1.Child2

*nlevel ( ltree ) → integer* - 경로의 레이블 수를 반환합니다. +
예) nlevel('Top.Child1.Child2') → 3

*index ( a ltree, b ltree ) → integer* - a에서 b가 처음으로 나타나는 위치를 반환하거나 찾을 수 없으면 -1을 반환합니다. +
예) index('0.1.2.3.5.4.5.6.8.5.6.8', '5.6') → 6

*index ( a ltree, b ltree, offset integer ) → integer* - a에서 b가 처음으로 나타나는 위치를 반환하거나, 찾을 수 없으면 -1을 반환합니다. 검색은 오프셋 위치에서 시작됩니다. 음수 오프셋은 경로 끝에서 시작 - 오프셋 레이블을 의미합니다. +
예) index('0.1.2.3.5.4.5.6.8.5.6.8', '5.6', -4) → 9

*text2ltree ( text ) → ltree* - 텍스트를 ltree로 캐스트합니다.

*ltree2text ( ltree ) → text* - ltree를 텍스트로 캐스트합니다.

*lca ( ltree [, ltree [, ... ]] ) → ltree* - 경로의 가장 긴 공통 조상을 계산합니다.(최대 8개의 인수가 지원됨) +
예) lca('1.2.3', '1.2.3.4.5.6') → 1.2

*lca ( ltree[] ) → ltree* - 배열에 잇는 경로의 가장 긴 공통 조상을 계산합니다. +
예) lca(array['1.2.3'::ltree,'1.2.3.4']) → 1.2

* indexes

ltree는 표시된 연산자의 속도를 높일 수 있는 여러 유형의 인덱스를 지원합니다.

*B-트리 인덱스 ltree: <, <=, =, >=,>*

*ltree에 대한 GiST 인덱스(gist_ltree_opsopclass): <, <=, =, >=, >, @>, <@, @, ~,?*

*ltree[]에 대한 GiST 인덱스(gist__ltree_ops opclass): ltree[] <@ ltree, ltree @> ltree[], @, ~, ?*

* transforms

PL/Python의 유형에 대한 변환을 구현하는 추가 extension을 사용할 수 있습니다. ltree_plpythonu, ltree_plpythonu2u, ltree_plpythonu3u extension입니다. 이를 설치하고 함수르 생성할 때 지정하면 ltree 값이 python 목록에 매핑됩니다.(반대의 경우는 아직 지원하지 않습니다.)


== ltree 예시
ltree 에대한 예시와 이를 간단하게 설명합니다.

[source, sql]
----
--데이터는 contrib/ltree/ltreetest.sql에서도 제공합니다.
CREATE TABLE test (path ltree);
INSERT INTO test VALUES ('Top');
INSERT INTO test VALUES ('Top.Science');
INSERT INTO test VALUES ('Top.Science.Astronomy');
INSERT INTO test VALUES ('Top.Science.Astronomy.Astrophysics');
INSERT INTO test VALUES ('Top.Science.Astronomy.Cosmology');
INSERT INTO test VALUES ('Top.Hobbies');
INSERT INTO test VALUES ('Top.Hobbies.Amateurs_Astronomy');
INSERT INTO test VALUES ('Top.Collections');
INSERT INTO test VALUES ('Top.Collections.Pictures');
INSERT INTO test VALUES ('Top.Collections.Pictures.Astronomy');
INSERT INTO test VALUES ('Top.Collections.Pictures.Astronomy.Stars');
INSERT INTO test VALUES ('Top.Collections.Pictures.Astronomy.Galaxies');
INSERT INTO test VALUES ('Top.Collections.Pictures.Astronomy.Astronauts');
CREATE INDEX path_gist_idx ON test USING GIST (path);
CREATE INDEX path_idx ON test USING BTREE (path);
----

이를 트리로 나타내면 아래와 같습니다.

                       Top
                     /   |  \
             Science Hobbies Collections
                 /       |              \
        Astronomy   Amateurs_Astronomy Pictures
           /  \                            |
Astrophysics  Cosmology                Astronomy
                                        /  |    \
                                 Galaxies Stars Astronauts

상속도 가능합니다.
[source, sql]
----
SELECT path FROM test WHERE path <@ 'Top.Science';
                path
------------------------------------
 Top.Science
 Top.Science.Astronomy
 Top.Science.Astronomy.Astrophysics
 Top.Science.Astronomy.Cosmology
(4 rows)
----

경로 일치의 예입니다.
[source,sql]
----
SELECT path FROM test WHERE path ~ '*.Astronomy.*';
                     path
-----------------------------------------------
 Top.Science.Astronomy
 Top.Science.Astronomy.Astrophysics
 Top.Science.Astronomy.Cosmology
 Top.Collections.Pictures.Astronomy
 Top.Collections.Pictures.Astronomy.Stars
 Top.Collections.Pictures.Astronomy.Galaxies
 Top.Collections.Pictures.Astronomy.Astronauts
(7 rows)

SELECT path FROM test WHERE path ~ '*.!pictures@.Astronomy.*';
                path
------------------------------------
 Top.Science.Astronomy
 Top.Science.Astronomy.Astrophysics
 Top.Science.Astronomy.Cosmology
(3 rows)
----

전체 텍스트 검색의 예입니다.
[source, sql]
----
SELECT path FROM test WHERE path @ 'Astro*% & !pictures@';
                path
------------------------------------
 Top.Science.Astronomy
 Top.Science.Astronomy.Astrophysics
 Top.Science.Astronomy.Cosmology
 Top.Hobbies.Amateurs_Astronomy
(4 rows)

SELECT path FROM test WHERE path @ 'Astro* & !pictures@';
                path
------------------------------------
 Top.Science.Astronomy
 Top.Science.Astronomy.Astrophysics
 Top.Science.Astronomy.Cosmology
(3 rows)
----

함수를 사용한 경로 구성입니다.
[source, sql]
----
SELECT subpath(path,0,2)||'Space'||subpath(path,2) FROM test WHERE path <@ 'Top.Science.Astronomy';
                 ?column?
------------------------------------------
 Top.Science.Space.Astronomy
 Top.Science.Space.Astronomy.Astrophysics
 Top.Science.Space.Astronomy.Cosmology
(3 rows)
----

경로의 지정된 위치에 레이블을 삽입하는 SQL 함수를 만들어 이를 단순화 할 수 있습니다.
[source, sql]
----
CREATE FUNCTION ins_label(ltree, int, text) RETURNS ltree
    AS 'select subpath($1,0,$2) || $3 || subpath($1,$2);'
    LANGUAGE SQL IMMUTABLE;

SELECT ins_label(path,2,'Space') FROM test WHERE path <@ 'Top.Science.Astronomy';
                ins_label
------------------------------------------
 Top.Science.Space.Astronomy
 Top.Science.Space.Astronomy.Astrophysics
 Top.Science.Space.Astronomy.Cosmology
(3 rows)
----