= pgstattuple
:toc: 
:toc-title: 목차
:sectlinks:
:sectnums:

== pgstattuple 설명
pgstattuple 모듈은 튜플 수준 통계를 얻기 위한 다양한 함수를 제공합니다. 함수의 종류 및 자세한 내용은 아래와 같습니다.

* pgstattuple(regclass or text) returns record +
relation의 물리적 길이, dead튜플의 백분율 및 기타 정보를 반환합니다. 사용자가 vacuum이 필요한지 여부를 결정하는데 도움이 될 수 있고, 인수는 대상 관계의 이름, OID, TEXT입니다.
return 값은 아래와 같습니다. 이 함수는 read lock만 획득할 수 있고, HeapTupleSatisfiesDirty가 false를 반환하면 dead 튜플이라고 판단합니다.

[width="80%",cols="3*",options="header"]
|===
|column | 유형 | 설명
|table_len | bigint | 물리적 relation 길이(byte)
|tuple_count | bigint |	live 튜플 수
|tuple_len | bigint | live 튜플의 총 길이(바이트)
|tuple_percent | float8 | live 튜플의 백분율
|dead_tuple_count | bigint | dead 튜플의 수
|dead_tuple_len | bigint | dead 튜플의 총 길이(바이트)
|dead_tuple_percent | float8 | dead 튜플의 백분율
|free_space | bigint | 총 여유 공간(바이트)
|free_percent | float8 | 여유 공간 비율
	
|===

* pgstatindex(regclass or text) returns record +
B-트리 인덱스에 대한 정보를 보여주는 레코드를 반환합니다.

[width="80%",cols="3*",options="header"]
|===
|column | 유형 | 설명
|version | integer | B-트리 버전
|tree_level	| integer | root 페이지의 tree level
|index_size	| bigint | 총 인덱스 크기(바이트)
|root_block_no | bigint | root 페이지의 위치(없으면 0)
|internal_pages | bigint | "내부" (상위 수준) 페이지 수
|leaf_pages	| bigint | leaf 페이지 수
|empty_pages | bigint | empty 페이지 수
|deleted_pages | bigint | deleted 페이지 수
|avg_leaf_density | float8 | leaf 페이지의 평균 밀도
|leaf_fragmentation | float8 | leaf 페이지 조각화

|===

* pgstatginindex(regclass) returns record +
GIN 인덱스에 대한 정보를 보여주는 레코드를 반환합니다.

[width="80%",cols="3*",options="header"]
|===
|column | 유형 | 설명
|version | integer | gin 버전 번호
|pending_pages | integer | 보류 목록의 페이지 수
|pending_tuples | bigint | 보류 목록의 튜플 수

|===

* pgstathashindex(regclass) returns record + 
HASH 인덱스에 대한 정보를 보여주는 레코드를 반환합니다.

[width="80%",cols="3*",options="header"]
|===
|column | 유형 | 설명
|version | integer | 해시 버전 번호
|bucket_pages | bigint | 버킷 페이지 수
|overflow_pages | bigint | 오버플로 페이지 수
|bitmap_pages | bigint | 비트맵 페이지 수
|unused_pages |	bigint | 미사용 페이지 수
|live_items | bigint | 라이브 튜플 수
|dead_tuples | bigint | 죽은 튜플의 수
|free_percent | float | 여유 공간 비율

|===

* pg_relpages(regclass or text) returns bigint + 
relation의 페이지 수를 반환합니다.

* pgstattuple_approx(regclass) returns record +
대략적인 결과를 반환하는 더 빠른 대안입니다. pgstattuple은 전체 테이블 스캔을 수행하고 live 및 dead 튜플과 여유 공간의 정확한 수를 반환하는데, pgstattuple_approx는 전체 테이블 스캔을 피하고 근사치로 live 및 dead 튜플과 여유 공간의 통계를 반환합니다(dead 튜플은 정확하게 반환함). visibility map에 의거하여 페이지를 건너뛰는 방식으로 수행합니다.

[width="80%",cols="3*",options="header"]
|===
|column | 유형 | 설명
|table_len | bigint | 물리적 relation 길이(byte)
|scanned_percent | float8 | 스캔한 테이블의 비율
|approx_tuple_count | bigint |	live 튜플 수
|approx_tuple_len | bigint | live 튜플의 총 길이(바이트)
|approx_tuple_percent | float8 | live 튜플의 백분율
|dead_tuple_count | bigint | dead 튜플의 수
|dead_tuple_len | bigint | dead 튜플의 총 길이(바이트)
|dead_tuple_percent | float8 | dead 튜플의 백분율
|approx_free_space | bigint | 총 여유 공간(바이트)
|approx_free_percent | float8 | 여유 공간 비율
	
|===

== pgstattuple 예시
pgstattuple 함수 조회
[source, sql]
----
postgres=# SELECT * FROM pgstattuple('pg_catalog.pg_proc'); 
-[ RECORD 1 ]------+--------
table_len          | 1327104
tuple_count        | 4219
tuple_len          | 1094969
tuple_percent      | 82.51
dead_tuple_count   | 179
dead_tuple_len     | 38275
dead_tuple_percent | 2.88
free_space         | 155716
free_percent       | 11.73
----

pgstatindex 함수 조회
[source, sql]
----
SELECT * FROM pgstatindex('pg_cast_oid_index'); 
-[ RECORD 1 ]------+------
version            | 4
tree_level         | 0
index_size         | 16384
root_block_no      | 1
internal_pages     | 0
leaf_pages         | 1
empty_pages        | 0
deleted_pages      | 0
avg_leaf_density   | 68.74
leaf_fragmentation | 0
----

pgstatginindex 함수 조회
[source, sql]
----
postgres=# select * from pgstatginindex('test_ginidx');
-[ RECORD 1 ]--+--
version        | 2
pending_pages  | 0
pending_tuples | 0
----

pgstathashindex 함수 조회
[source, sql]
----
postgres=# select * from pgstathashindex('test_hashidx');
-[ RECORD 1 ]--+----
version        | 4
bucket_pages   | 4
overflow_pages | 0
bitmap_pages   | 1
unused_pages   | 0
live_items     | 0
dead_items     | 0
free_percent   | 100
----

pgstattuple_approx 함수 조회
[source, sql]
----
postgres=# SELECT * FROM pgstattuple_approx('pg_catalog.pg_proc'::regclass);
-[ RECORD 1 ]--------+------------------
table_len            | 1335296
scanned_percent      | 48
approx_tuple_count   | 3429
approx_tuple_len     | 1140904
approx_tuple_percent | 85.44202933282209
dead_tuple_count     | 179
dead_tuple_len       | 38275
dead_tuple_percent   | 2.866405650881902
approx_free_space    | 142620
approx_free_percent  | 10.68077789493865
----
